// Corriston Master Prospect Database v1
// DO NOT merge into WSS CRM. This is a separate company-wide database.
// Source: Web research — LinkedIn public profiles, company sites, Crunchbase, podcast appearances.
// Nothing sent. Nothing imported. Gary review required before any outreach.

export type ProductFit = "WSS" | "CBO" | "IntrynSync" | "ConversionHealth" | "Multiple";
export type Priority = "P1" | "P2" | "P3";
export type Relationship = "1st Degree" | "2nd Degree" | "3rd Degree" | "Unknown";
export type Segment = "Agencies" | "Home Services Scale" | "RevOps / MarOps" | "B2B SaaS" | "Ecommerce" | "Professional Services";
export type ProspectStatus = "new" | "contacted" | "replied" | "meeting_set" | "closed" | "not_a_fit";

export interface CCProspect {
  id: number;
  company_name: string;
  contact_name: string;
  title: string;
  linkedin_profile_url: string;
  linkedin_company_url: string;
  industry: string;
  company_size: string;
  website: string;
  city: string;
  state: string;
  email: string;
  phone: string;
  source: string;
  notes: string;
  product_fit: ProductFit;
  qualification_wss: boolean;
  qualification_cbo: boolean;
  qualification_intrynsync: boolean;
  qualification_conversionhealth: boolean;
  priority: Priority;
  relationship: Relationship;
  segment: Segment;
  status: ProspectStatus;
}

export const CC_PROSPECTS: CCProspect[] = [
  { id: 1, company_name: "Disruptive Advertising", contact_name: "Jacob Baadsgaard", title: "Founder & CEO", linkedin_profile_url: "linkedin.com/in/jakebaadsgaard", linkedin_company_url: "linkedin.com/company/disruptive-advertising", industry: "Digital Marketing Agency", company_size: "51-200", website: "disruptiveadvertising.com", city: "Pleasant Grove", state: "UT", email: "", phone: "", source: "Web Research", notes: "Google Premier Partner + Meta Business Partner managing multi-platform budgets for 100s of clients; actively sells CRO services.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P1", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 2, company_name: "Directive Consulting", contact_name: "Garrett Mehrguth", title: "Co-Founder & CEO", linkedin_profile_url: "linkedin.com/in/garrettmehrguth", linkedin_company_url: "linkedin.com/company/directive-consulting", industry: "B2B SaaS Performance Marketing Agency", company_size: "101-250", website: "directiveconsulting.com", city: "Irvine", state: "CA", email: "", phone: "", source: "Web Research", notes: "Most prominent B2B SaaS paid media agency in the US. Clients: Dropbox / AWS / Gong. Sells CRO auditing.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P1", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 3, company_name: "KlientBoost", contact_name: "Johnathan Dane", title: "Founder & CEO", linkedin_profile_url: "linkedin.com/in/johnathandane", linkedin_company_url: "linkedin.com/company/klientboost", industry: "PPC & CRO Agency", company_size: "88-100", website: "klientboost.com", city: "Costa Mesa", state: "CA", email: "", phone: "", source: "Web Research", notes: "Core pitch is PPC + CRO combined. 200+ active clients. Stanford guest lecturer. Prolific publisher.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P1", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 4, company_name: "Jordan Digital Marketing", contact_name: "Tyler Jordan", title: "Founder & CEO", linkedin_profile_url: "linkedin.com/in/tylerandrewjordan", linkedin_company_url: "linkedin.com/company/jordan-digital-marketing", industry: "Digital Marketing Agency", company_size: "35", website: "jordandigitalmarketing.com", city: "San Francisco", state: "CA", email: "", phone: "", source: "Web Research", notes: "Exclusively focused on high-growth SaaS. Manages paid across Google / YouTube / Facebook / LinkedIn. LP at MKT1.", product_fit: "CBO", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 5, company_name: "Hawke Media", contact_name: "Erik Huberman", title: "Founder & CEO", linkedin_profile_url: "linkedin.com/in/erikhuberman", linkedin_company_url: "linkedin.com/company/hawke-media", industry: "eCommerce / DTC Marketing Agency", company_size: "300+", website: "hawkemedia.com", city: "Los Angeles", state: "CA", email: "", phone: "", source: "Web Research", notes: "5,000+ ecommerce brand clients. Built Hawke.AI — strong appetite for media efficiency tools.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P1", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 6, company_name: "PPC Boost", contact_name: "Brian Lasonde", title: "Founder & CEO", linkedin_profile_url: "linkedin.com/in/blasonde", linkedin_company_url: "linkedin.com/company/ppc-boost", industry: "eCommerce PPC Agency", company_size: "10", website: "ppcboost.com", city: "Denver", state: "CO", email: "", phone: "", source: "Web Research", notes: "Boutique ecommerce PPC agency. Clients spending $50K-$1M+/month on Google + Meta.", product_fit: "CBO", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 7, company_name: "Logical Position", contact_name: "Michael Weinhouse", title: "Founder & Co-CEO", linkedin_profile_url: "linkedin.com/in/mpweinhouse", linkedin_company_url: "linkedin.com/company/logical-position", industry: "Digital Marketing Agency", company_size: "200-500", website: "logicalposition.com", city: "Portland", state: "OR", email: "", phone: "", source: "Web Research", notes: "One of the largest independent PPC agencies in the US. Inc. 500 honoree.", product_fit: "CBO", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 8, company_name: "Jordan Digital Marketing", contact_name: "Laura Schiele", title: "Head of Performance Marketing", linkedin_profile_url: "linkedin.com/in/laura-schiele", linkedin_company_url: "linkedin.com/company/jordan-digital-marketing", industry: "Digital Marketing Agency", company_size: "35", website: "jordandigitalmarketing.com", city: "Burlington", state: "VT", email: "", phone: "", source: "Web Research", notes: "Manages paid media strategy for B2B SaaS clients. Publishes on Search Engine Land + MarTech. Advanced analytics.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P1", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 9, company_name: "G2", contact_name: "Palmer Houchins", title: "VP & Head of Marketing", linkedin_profile_url: "linkedin.com/in/palmerhouchins", linkedin_company_url: "linkedin.com/company/g2dotcom", industry: "B2B SaaS / Software Review", company_size: "500-1000", website: "g2.com", city: "Atlanta", state: "GA", email: "", phone: "", source: "Web Research", notes: "Former Mailchimp + CallRail. Significant multi-platform paid media. Demand Gen Visionaries podcast.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P1", relationship: "Unknown", segment: "B2B SaaS", status: "new" },
  { id: 10, company_name: "iHerb", contact_name: "Neil Folgate", title: "SVP Global Marketing", linkedin_profile_url: "linkedin.com/in/neilfolgate", linkedin_company_url: "linkedin.com/company/iherb", industry: "eCommerce / Health & Wellness", company_size: "1000-5000", website: "iherb.com", city: "Pasadena", state: "CA", email: "", phone: "", source: "Web Research", notes: "$200M+ annual ad spend. 20+ years ecommerce SEM/PPC. Global conversion signal fragmentation.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P1", relationship: "Unknown", segment: "Ecommerce", status: "new" },
  { id: 11, company_name: "Bombas", contact_name: "Michelle DeStein", title: "Director of Growth Marketing", linkedin_profile_url: "linkedin.com/in/michelle-destein", linkedin_company_url: "linkedin.com/company/bombas", industry: "eCommerce / DTC Apparel", company_size: "200-500", website: "bombas.com", city: "Brooklyn", state: "NY", email: "", phone: "", source: "Web Research", notes: "Shark Tank brand. $2B+ lifetime sales. Former Amazon Sr. Media Analyst + Ring Acquisition Marketing.", product_fit: "ConversionHealth", qualification_wss: false, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P2", relationship: "Unknown", segment: "Ecommerce", status: "new" },
  { id: 12, company_name: "CyberArk", contact_name: "Adeline Martin", title: "Paid Media Director", linkedin_profile_url: "linkedin.com/in/adeline-m-17621a13", linkedin_company_url: "linkedin.com/company/cyberark", industry: "B2B Cybersecurity SaaS", company_size: "5000-10000", website: "cyberark.com", city: "Newton", state: "MA", email: "", phone: "", source: "Web Research", notes: "NASDAQ: CYBR. Enterprise SaaS. High CPCs on Google + LinkedIn. Long cycles make ConversionHealth critical.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P2", relationship: "Unknown", segment: "B2B SaaS", status: "new" },
  { id: 13, company_name: "Single Grain", contact_name: "Eric Siu", title: "CEO", linkedin_profile_url: "linkedin.com/in/ericosiu", linkedin_company_url: "linkedin.com/company/single-grain", industry: "Digital Marketing Agency", company_size: "74", website: "singlegrain.com", city: "Los Angeles", state: "CA", email: "", phone: "", source: "Web Research", notes: "Marketing School podcast (1.6M+ downloads/month). Agency clients: Uber / Salesforce / Amazon. Channel partner potential.", product_fit: "CBO", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 14, company_name: "Tinuiti", contact_name: "Zach Morrison", title: "CEO", linkedin_profile_url: "linkedin.com/in/zmorrison", linkedin_company_url: "linkedin.com/company/tinuiti", industry: "Performance Marketing Agency", company_size: "1000+", website: "tinuiti.com", city: "New York", state: "NY", email: "", phone: "", source: "Web Research", notes: "Largest independent performance marketing agency in US. $3B+ media under management.", product_fit: "CBO", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 15, company_name: "Workshop Digital", contact_name: "Morgan Jarvis", title: "Director of Paid Media", linkedin_profile_url: "linkedin.com/in/morganmackenziejarvis", linkedin_company_url: "linkedin.com/company/workshop-digital-llc", industry: "Digital Marketing Agency", company_size: "20-50", website: "workshopdigital.com", city: "Richmond", state: "VA", email: "", phone: "", source: "Web Research", notes: "Best Small PPC Agency — US Search Awards 2025. Publishes on AI + first-party data + offline conversion reporting.", product_fit: "Multiple", qualification_wss: false, qualification_cbo: true, qualification_intrynsync: false, qualification_conversionhealth: true, priority: "P1", relationship: "Unknown", segment: "Agencies", status: "new" },
  { id: 16, company_name: "Any Hour Group", contact_name: "Mike Wilson", title: "CMO", linkedin_profile_url: "linkedin.com/in/mike-wilson-101490187", linkedin_company_url: "linkedin.com/company/any-hour-services", industry: "Home Services (HVAC / Plumbing / Electrical)", company_size: "1500+", website: "anyhourgroup.com", city: "Orem", state: "UT", email: "", phone: "", source: "Web Research", notes: "PE-backed. 21+ brands / 29 locations / $300M+ revenue. CMO overseeing web presence for all brands.", product_fit: "WSS", qualification_wss: true, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "Home Services Scale", status: "new" },
  { id: 17, company_name: "Southern Home Services", contact_name: "James Lyons", title: "Director of Marketing", linkedin_profile_url: "linkedin.com/in/jimmy-john-lyons", linkedin_company_url: "linkedin.com/company/southernhvac", industry: "Home Services (HVAC / Plumbing / Electrical)", company_size: "501-1000", website: "southernhomeservices.com", city: "Maitland", state: "FL", email: "", phone: "", source: "Web Research", notes: "Gryphon-backed. 10+ local brands across 11 states. Director of Marketing manages all web properties.", product_fit: "WSS", qualification_wss: true, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "Home Services Scale", status: "new" },
  { id: 18, company_name: "Redwood Services", contact_name: "Raj Midha", title: "Chief Marketing Officer", linkedin_profile_url: "linkedin.com/in/raj-midha-165590", linkedin_company_url: "linkedin.com/company/redwood-services-llc", industry: "Home Services (HVAC / Plumbing / Electrical)", company_size: "501-1000", website: "redwoodservices.com", city: "Memphis", state: "TN", email: "", phone: "", source: "Web Research", notes: "18 partner companies / $500M+ revenue. Freshly appointed CMO building marketing infrastructure.", product_fit: "WSS", qualification_wss: true, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "Home Services Scale", status: "new" },
  { id: 19, company_name: "JP Pest Services", contact_name: "Joe Pestana", title: "President", linkedin_profile_url: "linkedin.com/in/joe-pestana-21921131", linkedin_company_url: "linkedin.com/company/jp-pest-services", industry: "Pest Control", company_size: "84", website: "jppestservices.com", city: "Milford", state: "NH", email: "", phone: "", source: "Web Research", notes: "Largest + oldest pest control in NH. Multi-state (NH/MA/ME/VT). Family-owned at scale needing professional web support.", product_fit: "WSS", qualification_wss: true, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "Home Services Scale", status: "new" },
  { id: 20, company_name: "Green Pest Solutions", contact_name: "Matt Jesson", title: "CEO / Founder", linkedin_profile_url: "", linkedin_company_url: "linkedin.com/company/green-pest-solutions", industry: "Pest Control / Lawn Care", company_size: "100+", website: "greenpestsolutions.com", city: "West Chester", state: "PA", email: "", phone: "", source: "Web Research", notes: "Largest locally-owned pest control in PA/NJ/DE. Dual-brand. Titan 100. LinkedIn slug not confirmed — search directly.", product_fit: "WSS", qualification_wss: true, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "Home Services Scale", status: "new" },
  { id: 21, company_name: "Carolina Pest Management", contact_name: "Kristin Dodd-Tarleton", title: "President", linkedin_profile_url: "linkedin.com/in/kristin-dodd-00a8236", linkedin_company_url: "linkedin.com/company/carolina-pest-management", industry: "Pest Control", company_size: "75+", website: "carolinapest.com", city: "Monroe", state: "NC", email: "", phone: "", source: "Web Research", notes: "75+ year old multi-location family business. President is hands-on and open to solutions that reduce operational burden.", product_fit: "WSS", qualification_wss: true, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "Home Services Scale", status: "new" },
  { id: 22, company_name: "Horizon Pest Control", contact_name: "Bernie Holst III", title: "CEO", linkedin_profile_url: "linkedin.com/in/bernie-holst", linkedin_company_url: "linkedin.com/company/horizon-pest-control", industry: "Pest Control", company_size: "50+", website: "horizonpestcontrol.com", city: "Midland Park", state: "NJ", email: "", phone: "", source: "Web Research", notes: "50+ year old firm. Multiple NJ/NY locations. Family-led business professionalizing digital marketing ops.", product_fit: "WSS", qualification_wss: true, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "Home Services Scale", status: "new" },
  { id: 23, company_name: "Predator Services of America", contact_name: "Christopher Kyriakides", title: "President", linkedin_profile_url: "linkedin.com/in/christopher-kyriakides-a243b11a7", linkedin_company_url: "", industry: "Pest Control / Lawn & Ornamental", company_size: "10-25", website: "", city: "FL", state: "FL", email: "", phone: "", source: "Web Research", notes: "Multi-service certified operator. Growing. Likely handles web presence manually. Verify via direct search.", product_fit: "WSS", qualification_wss: true, qualification_cbo: false, qualification_intrynsync: false, qualification_conversionhealth: false, priority: "P3", relationship: "Unknown", segment: "Home Services Scale", status: "new" },
  { id: 24, company_name: "RevOps Marketing LLC", contact_name: "Henry Tran", title: "Marketing Operations Director", linkedin_profile_url: "linkedin.com/in/gethenry", linkedin_company_url: "", industry: "RevOps / Marketing Operations Consulting", company_size: "1-10", website: "", city: "Los Angeles", state: "CA", email: "", phone: "", source: "Web Research", notes: "Independent MarOps/RevOps consultant. Marketo / HubSpot / Salesforce certified. Keynotes on AI for Marketers.", product_fit: "IntrynSync", qualification_wss: false, qualification_cbo: false, qualification_intrynsync: true, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "RevOps / MarOps", status: "new" },
  { id: 25, company_name: "Revenue Pulse", contact_name: "Morgan Malone", title: "RevOps Consultant", linkedin_profile_url: "linkedin.com/in/morgancmalone", linkedin_company_url: "linkedin.com/company/revenue-pulse", industry: "Marketing & Sales Operations Consulting", company_size: "51", website: "revenuepulse.com", city: "San Diego", state: "CA", email: "", phone: "", source: "Web Research", notes: "Leading MarOps consultancy. Marketo / HubSpot / Pardot / Salesforce / Eloqua. Exact multi-tool complexity IntrynSync solves.", product_fit: "IntrynSync", qualification_wss: false, qualification_cbo: false, qualification_intrynsync: true, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "RevOps / MarOps", status: "new" },
  { id: 26, company_name: "RevOps Automated", contact_name: "Natalie Furness", title: "CEO", linkedin_profile_url: "linkedin.com/in/nataliefurness", linkedin_company_url: "linkedin.com/company/revops-automated", industry: "RevOps Consulting", company_size: "10-25", website: "revopsautomated.com", city: "United Kingdom", state: "", email: "", phone: "", source: "Web Research", notes: "HubSpot Diamond Partner + Salesforce Partner. B2B leaders scaling $2M-$200M. North America clients.", product_fit: "IntrynSync", qualification_wss: false, qualification_cbo: false, qualification_intrynsync: true, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "RevOps / MarOps", status: "new" },
  { id: 27, company_name: "Self-Employed", contact_name: "Adam Enright", title: "RevOps & MOPS Evangelist", linkedin_profile_url: "linkedin.com/in/adamenright", linkedin_company_url: "", industry: "RevOps / Marketing Operations Consulting", company_size: "1", website: "", city: "Los Angeles", state: "CA", email: "", phone: "", source: "Web Research", notes: "Marketo MCE + Salesforce Admin + HubSpot certified. Podcast host (How We RevOps). MarketingOps.com ambassador. Channel partner potential.", product_fit: "IntrynSync", qualification_wss: false, qualification_cbo: false, qualification_intrynsync: true, qualification_conversionhealth: false, priority: "P1", relationship: "Unknown", segment: "RevOps / MarOps", status: "new" },
  { id: 28, company_name: "VelocityEHS", contact_name: "Ashley Vonella", title: "Sr. Director of Revenue Operations", linkedin_profile_url: "linkedin.com/in/ashleyvonella", linkedin_company_url: "linkedin.com/company/msdsonline", industry: "EHS SaaS Software", company_size: "641", website: "ehs.com", city: "Chicago", state: "IL", email: "", phone: "", source: "Web Research", notes: "Mid-market SaaS. $70.5M revenue. GTM RevOps Sr. Director managing complex multi-tool revenue stack.", product_fit: "IntrynSync", qualification_wss: false, qualification_cbo: false, qualification_intrynsync: true, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "RevOps / MarOps", status: "new" },
  { id: 29, company_name: "Doppel", contact_name: "Margy Shomaker", title: "RevOps Manager — Systems & Tooling", linkedin_profile_url: "linkedin.com/in/margyshomaker", linkedin_company_url: "linkedin.com/company/doppel", industry: "AI / Cybersecurity SaaS", company_size: "347", website: "doppel.com", city: "Covina", state: "CA", email: "", phone: "", source: "Web Research", notes: "4x Marketo Certified Expert. Salesforce + HubSpot RevOps stack. Series C / $129M raised.", product_fit: "IntrynSync", qualification_wss: false, qualification_cbo: false, qualification_intrynsync: true, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "B2B SaaS", status: "new" },
  { id: 30, company_name: "Fractional RevOps", contact_name: "Jeremy Lamande", title: "Fractional RevOps Leader", linkedin_profile_url: "linkedin.com/in/jeremy-lamande", linkedin_company_url: "", industry: "RevOps Consulting", company_size: "1", website: "", city: "United States", state: "", email: "", phone: "", source: "Web Research", notes: "Fractional RevOps leader building RevOps systems for 5+ SaaS clients simultaneously. Channel multiplier.", product_fit: "IntrynSync", qualification_wss: false, qualification_cbo: false, qualification_intrynsync: true, qualification_conversionhealth: false, priority: "P2", relationship: "Unknown", segment: "RevOps / MarOps", status: "new" },
];

export const CC_P1 = CC_PROSPECTS.filter(p => p.priority === "P1");
export const CC_WSS = CC_PROSPECTS.filter(p => p.qualification_wss);
export const CC_CBO = CC_PROSPECTS.filter(p => p.qualification_cbo);
export const CC_INTRYNSYNC = CC_PROSPECTS.filter(p => p.qualification_intrynsync);
export const CC_CONVERSIONHEALTH = CC_PROSPECTS.filter(p => p.qualification_conversionhealth);
export const CC_MULTI = CC_PROSPECTS.filter(p => p.product_fit === "Multiple");
