export type ServiceAreaCity = {
  city: string;
  neighborhoods: string[];
};

export type ServiceAreaInfo = {
  dma: string;
  mapLabel?: string;
  coverageCopy: string;
  cityGroups: ServiceAreaCity[];
};

export type SampleBusiness = {
  slug: string;
  systemKey: string;
  systemName: string;
  name: string;
  category: string;
  location: string;
  badge: string;
  tagline: string;
  headline: string;
  description: string;
  phoneLabel: string;
  phoneHref: string;
  email: string;
  address: string;
  hours: string[];
  heroImage: string;
  heroAlt: string;
  serviceSectionImage?: string;
  serviceSectionImageAlt?: string;
  trustSectionImage?: string;
  trustSectionImageAlt?: string;
  accent: string;
  dark: string;
  soft: string;
  nav: { href: string; label: string; page: SamplePage }[];
  servicesLabel: string;
  servicesIntro: string;
  services: { name: string; meta: string; body: string }[];
  proofLabel: string;
  proofIntro: string;
  proofItems: string[];
  aboutHeadline: string;
  aboutBody: string;
  localNeighborhoods?: string[];
  localCoverageIntro?: string;
  trustHeadline?: string;
  trustIntro?: string;
  ownerSection?: {
    eyebrow: string;
    title: string;
    body: string;
    bullets: string[];
    cardTitle: string;
    cardItems: string[];
  };
  localSection?: {
    eyebrow: string;
    title: string;
    body: string;
    items: string[];
  };
  trust: string[];
  contactPrompt: string;
  proofHeadline?: string;
  contactTitle?: string;
  formTitle?: string;
  formButtonLabel?: string;
  primaryCtaLabel?: string;
  emergencyServiceNote?: string;
  financingTopics?: string[];
  financingIntro?: string;
  serviceArea?: ServiceAreaInfo;
};

export type SamplePage = "home" | "services" | "about" | "proof" | "service-area" | "contact";

const nav = (
  base: string,
  servicesLabel = "Services",
  proofLabel = "Work",
  includeServiceArea = false,
) => [
  { href: base, label: "Home", page: "home" as const },
  { href: `${base}/services`, label: servicesLabel, page: "services" as const },
  ...(includeServiceArea ? [{ href: `${base}/service-areas`, label: "Service Areas", page: "service-area" as const }] : []),
  { href: `${base}/about`, label: "About", page: "about" as const },
  { href: `${base}/work`, label: proofLabel, page: "proof" as const },
  { href: `${base}/contact`, label: "Contact", page: "contact" as const },
];

export const SAMPLE_BUSINESSES: SampleBusiness[] = [
  {
    slug: "ridgeline-roofing",
    systemKey: "summit",
    systemName: "Summit",
    name: "Ridgeline Roofing",
    category: "Residential roofing",
    location: "Denver, CO",
    badge: "Demo Sample",
    tagline: "Roof repair, replacement, inspections, and storm response for Denver homes.",
    headline: "Roofing for hail, sun, and snow.",
    description: "A premium, estimate-first roofing website for homeowners who need a clear next step after leaks, age, wind, or hail.",
    phoneLabel: "(303) 555-0198",
    phoneHref: "tel:+13035550198",
    email: "hello@ridgelineroofing.example",
    address: "Denver Metro Demo Area, Denver, CO 80202",
    hours: ["Monday-Friday 7am-6pm", "Saturday 8am-2pm", "Emergency tarping triage by request"],
    heroImage: "https://images.unsplash.com/photo-1635424824849-1b09bdcc55b1?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Roofer working on a residential shingle roof",
    accent: "#f97316",
    dark: "#172033",
    soft: "#eef2f7",
    nav: nav("/templates/sample/ridgeline-roofing", "Services", "Projects", true),
    servicesLabel: "Roofing services",
    servicesIntro: "A roofing site should separate repair, replacement, storm damage, inspections, and emergency paths clearly.",
    services: [
      { name: "Roof Repair", meta: "Leaks, flashing, shingles, vents", body: "Stop active leaks and fix roof details before small issues become interior damage." },
      { name: "Roof Replacement", meta: "Asphalt shingle and impact-rated options", body: "Plan a full roof replacement with clear material choices, ventilation notes, and project timing." },
      { name: "Storm Damage", meta: "Hail and wind triage", body: "Document visible storm impact and understand whether repair, replacement, or temporary protection comes next." },
      { name: "Roof Inspections", meta: "Buying, selling, or post-storm", body: "Get a readable roof condition summary with priority issues and homeowner next steps." },
      { name: "Emergency Service", meta: "Temporary protection", body: "Call-first guidance for roof openings, water intrusion, and urgent storm exposure." },
      { name: "Insurance Claim Support", meta: "Documentation-ready notes", body: "Photo-forward scope notes and roof details for homeowner insurance conversations." },
    ],
    proofLabel: "Project signals",
    proofIntro: "Project pages should make the work feel concrete without inventing customer testimonials or results.",
    proofItems: ["Hail inspection checklist", "Before and after roof photos", "Flashing repair detail", "Emergency tarp plan", "Ventilation review", "Final cleanup walkthrough"],
    aboutHeadline: "A roofing company presented with clear service confidence.",
    aboutBody: "Ridgeline Roofing is a fictional Denver roofing sample built around homeowner urgency: visible phone paths, service details, storm context, and straightforward estimate requests.",
    emergencyServiceNote: undefined,
    financingTopics: ["Roof replacement", "Storm-related replacement", "Major re-tile projects"],
    financingIntro: "For large jobs, this sample keeps financing language next to replacement and major repair conversations.",
    serviceArea: {
      dma: "Denver DMA",
      coverageCopy: "This service-area structure clarifies which nearby cities are supported before owners request estimates.",
      cityGroups: [
        { city: "Denver", neighborhoods: ["Downtown", "Cap Hill", "Stapleton", "Highland", "Cherry Creek"] },
        { city: "Aurora", neighborhoods: ["Aurora Central", "Skyline", "Green Valley Ranch"] },
        { city: "Lakewood", neighborhoods: ["Downtown Lakewood", "Cultural District", "Morrison"] },
        { city: "Golden", neighborhoods: ["Downtown Golden", "Foothills"] },
        { city: "Englewood", neighborhoods: ["Cherry Hills", "Littleton", "Berkley"] },
      ],
    },
  trust: ["Estimate-first conversion path", "Roofing imagery above the fold", "Service area and emergency language", "No fake reviews or unverifiable claims"],
  contactPrompt: "Tell Ridgeline what happened, what kind of roof you have, and whether there is active leaking.",
  primaryCtaLabel: "Request a Roof Estimate",
  contactTitle: "Request a roof estimate.",
  formTitle: "Request a Roof Estimate",
  formButtonLabel: "Request Estimate",
  localCoverageIntro: "This sample shows metro coverage for Denver-area roofing with explicit coverage transparency before estimate requests.",
  localNeighborhoods: ["Denver", "Aurora", "Lakewood", "Golden", "Englewood"],
  localSection: {
    eyebrow: "Metro service clarity",
    title: "Confirm coverage before choosing your next step.",
    body: "A homeowner should be able to confirm city coverage, then click repair, replacement, or storm support with confidence.",
    items: ["Denver", "Aurora", "Lakewood", "Golden", "Englewood", "Commerce City"],
  },
  },
  {
    slug: "greenline-landscaping",
    systemKey: "summit",
    systemName: "Summit",
    name: "Greenline Landscaping",
    category: "Landscaping and outdoor services",
    location: "Raleigh, NC",
    badge: "Sample Business",
    tagline: "Seasonal cleanups, lawn care, planting, mulch, and small hardscape projects.",
    headline: "Outdoor spaces that look cared for every week.",
    description: "A high-trust landscaping website for homeowners who want maintenance, refreshes, and clear seasonal service packages.",
    phoneLabel: "(919) 555-0137",
    phoneHref: "tel:+19195550137",
    email: "hello@greenlinelandscaping.example",
    address: "1220 Glenwood Ave, Raleigh, NC 27605",
    hours: ["Monday-Friday 8am-5pm", "Saturday estimates by appointment", "Closed Sunday"],
    heroImage: "https://images.unsplash.com/photo-1605117882932-f9e32b03fea9?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Freshly landscaped front yard with green lawn and planting beds",
    accent: "#65a30d",
    dark: "#1f2a1f",
    soft: "#f0f7ea",
    nav: nav("/templates/sample/greenline-landscaping", "Services", "Projects", true),
    servicesLabel: "Landscaping services",
    servicesIntro: "A landscaping site needs service packages, seasonal timing, and examples of curb-appeal work.",
    services: [
      { name: "Weekly Lawn Care", meta: "Mow, edge, blow", body: "Routine maintenance for tidy yards, clean walkways, and consistent curb appeal." },
      { name: "Seasonal Cleanups", meta: "Spring and fall", body: "Leaf removal, bed cleanup, pruning, and prep for the next growing season." },
      { name: "Mulch & Bed Refresh", meta: "Color and weed control", body: "Fresh mulch, sharp bed edges, and planting-bed cleanup for a quick exterior lift." },
      { name: "Planting Plans", meta: "Shrubs, flowers, privacy", body: "Simple planting recommendations for sun, shade, privacy, and low-maintenance color." },
      { name: "Small Hardscapes", meta: "Stone borders and paths", body: "Walkway refreshes, stone borders, gravel areas, and practical outdoor improvements." },
      { name: "Irrigation Checks", meta: "Coverage and repairs", body: "Basic sprinkler checks, dry-zone notes, and repair recommendations." },
    ],
    proofLabel: "Outdoor work",
    proofIntro: "Landscaping proof can show project types and seasonal moments without pretending to be real client work.",
    proofItems: ["Front bed refresh", "Lawn maintenance route", "Backyard cleanup", "Mulch install", "Stone border detail", "Seasonal planting plan"],
    aboutHeadline: "A local landscaping site with immediate service clarity.",
    aboutBody: "Greenline Landscaping is a fictional Raleigh landscaping sample built for estimate requests, seasonal service education, and fast mobile contact.",
    emergencyServiceNote: "For weather events and urgent heat/cool exposure, keep call-first support at the top of service pages.",
    financingTopics: ["Major landscape refreshes", "Irrigation upgrades", "Small hardscape replacements"],
    financingIntro: "When projects are larger than routine care, this sample surfaces payment timing options alongside project-specific requests.",
    serviceArea: {
      dma: "Raleigh DMA",
      coverageCopy: "A local contractor sample should state coverage clearly so visitors can confirm service fit before reaching out.",
      cityGroups: [
        { city: "Raleigh", neighborhoods: ["North Hills", "Five Points", "Cameron Village", "Downtown"] },
        { city: "Wake Forest", neighborhoods: ["South Wake", "Eastwood", "Forestville"] },
        { city: "Cary", neighborhoods: ["Preston", "West Cary", "Briarcreek"] },
        { city: "Apex", neighborhoods: ["Summerfield", "Muirfield", "Downtown Apex"] },
        { city: "Holly Springs", neighborhoods: ["Holly Square", "East Holly", "Cedar Drive"] },
      ],
    },
  trust: ["Trade-specific hero image", "Clear service list", "Project-style visual cues", "Click-to-call and estimate paths"],
  contactPrompt: "Share your address area, yard size, and whether you need maintenance, cleanup, planting, or a project estimate.",
  localCoverageIntro: "This sample demonstrates area clarity for core Raleigh neighborhoods in a practical exterior-services context.",
  localNeighborhoods: ["Raleigh", "Cary", "Wake Forest", "Apex", "Holly Springs"],
  localSection: {
    eyebrow: "City and neighborhood fit",
    title: "Area confirmation before project planning.",
    body: "This sample should confirm where service coverage applies before users choose seasonal maintenance, plant refresh, or estimate requests.",
    items: ["Raleigh", "Cary", "Apex", "Holly Springs", "Wake Forest"],
  },
  },
  {
    slug: "northwind-hvac",
    systemKey: "summit",
    systemName: "Summit",
    name: "Northwind Heating & Air",
    category: "Heating and air",
    location: "Minneapolis, MN",
    badge: "Sample Business",
    tagline: "AC repair, AC installation, heating and furnace service, tune-ups, indoor air quality, and emergency HVAC help.",
    headline: "When comfort breaks, the next step should be obvious.",
    description: "A premium, service-first HVAC website for homeowners who need a fast next step for AC, heat, tune-ups, indoor air quality, or replacement planning.",
    phoneLabel: "(612) 555-0172",
    phoneHref: "tel:+16125550172",
    email: "service@northwindhvac.example",
    address: "2448 Lyndale Ave S, Minneapolis, MN 55405",
    hours: ["Monday-Friday 7:30am-6pm", "Saturday 8am-2pm", "Priority no-cool and no-heat requests by phone"],
    heroImage: "https://images.pexels.com/photos/32497161/pexels-photo-32497161.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1400&q=80",
    heroAlt: "HVAC technician inspecting an outdoor condenser unit for servicing and diagnostics",
    serviceSectionImage: "https://images.pexels.com/photos/6471911/pexels-photo-6471911.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1400&q=80",
    serviceSectionImageAlt: "Technician checking gauges on an outdoor AC unit during HVAC maintenance",
    trustSectionImage: "/templates/airflow-hvac-desktop.svg",
    trustSectionImageAlt: "HVAC airflow and temperature flow diagram",
    accent: "#0ea5e9",
    dark: "#0f2437",
    soft: "#eaf6fb",
    nav: nav("/templates/sample/northwind-hvac", "HVAC Services", "Projects", true),
    servicesLabel: "HVAC services",
    servicesIntro: "A strong HVAC website separates urgent repair, planned maintenance, replacement installs, air-quality questions, and quote requests so homeowners can choose the right next step fast.",
    services: [
      { name: "AC Repair", meta: "No-cool diagnostics", body: "Fast help for warm air, short cycling, weak airflow, thermostat issues, and cooling systems that cannot keep up." },
      { name: "AC Installation", meta: "Replacement planning", body: "Clear replacement estimate paths for aging systems, right-sized options, efficiency goals, and financing questions." },
      { name: "Heating & Furnace", meta: "No-heat and winter comfort", body: "A calm service path for furnace problems, heat pump questions, ignition issues, and winter comfort concerns." },
      { name: "Maintenance Plans", meta: "Tune-ups and recurring care", body: "Spring and fall tune-up language, priority scheduling, filter reminders, and recurring comfort checks." },
      { name: "Indoor Air Quality", meta: "Filters, humidity, airflow", body: "Plain-language guidance for filtration, humidity, ventilation, stale rooms, dust concerns, and comfort from room to room." },
      { name: "Emergency Service", meta: "Urgent comfort calls", body: "Call-first guidance for no-cool, no-heat, unsafe temperatures, water near equipment, and urgent system failure." },
    ],
    proofLabel: "HVAC service proof",
    proofIntro: "Instead of fake testimonials, this sample shows the service situations a real HVAC website should make easy to understand: urgent comfort calls, seasonal maintenance, install estimates, and service-area clarity.",
    proofItems: ["No-cool dispatch path", "Furnace outage request", "Tune-up reminder", "Replacement quote next step", "Financing question", "Service-area confirmation"],
    aboutHeadline: "A local HVAC company homeowners can understand in one minute.",
    aboutBody: "Northwind Heating & Air is a fictional Minneapolis HVAC sample with a calm, service-first voice: what is wrong, where the homeowner is, how urgent it is, and what happens next.",
    trustHeadline: "Why homeowners would feel safe calling",
    trustIntro: "Northwind avoids vague contractor language and puts the homeowner's immediate question first: can you help, how do I ask, and what should I expect next?",
    emergencyServiceNote: "When comfort is unsafe, a direct call option should sit near the top of every important page.",
    financingTopics: ["Replacement installs", "Major repairs", "System upgrades"],
    financingIntro: "For high-cost HVAC decisions, show financing options near replacement and upgrade pathways before estimate requests.",
    serviceArea: {
      dma: "Minneapolis DMA",
      coverageCopy: "Service coverage is organized by city and neighborhood so homeowners can confirm local fit before submitting details.",
      cityGroups: [
        { city: "Minneapolis", neighborhoods: ["Downtown", "Northeast", "Southeast", "South Minneapolis", "Nicollet Island"] },
        { city: "St. Paul", neighborhoods: ["Macalester", "Summit Hill", "Summit Avenue", "West Side"] },
        { city: "Bloomington", neighborhoods: ["Normandale", "Wayzata Circle", "Eden Prairie"] },
        { city: "Edina", neighborhoods: ["Morningside", "Highlands", "West Country"] },
        { city: "Plymouth", neighborhoods: ["Meadow Ridge", "The Highlands", "Northridge"] },
      ],
    },
    ownerSection: {
      eyebrow: "Human trust",
      title: "Meet the kind of HVAC company this site is built for.",
      body: "Northwind is written like a small local HVAC team that knows a broken AC is not an abstract service category. It is a hot house, a sleeping baby, an older parent, or a workday interrupted by a system that stopped keeping up.",
      bullets: ["Plain-language repair paths", "No-pressure quote language", "Seasonal maintenance reminders", "A service form that asks what dispatch needs first"],
      cardTitle: "Sample trust language",
      cardItems: ["Local service team", "Repair and replacement guidance", "Respectful in-home communication", "No invented reviews or results"],
    },
    localSection: {
      eyebrow: "Local clarity",
      title: "Built for Minneapolis-area service calls.",
      body: "A real HVAC site should make service areas, urgent availability, maintenance plans, replacement quotes, and financing questions easy to find before someone fills out a form.",
      items: ["Minneapolis", "St. Paul", "Edina", "Bloomington", "Maple Grove", "Plymouth"],
    },
  trust: ["Clear no-cool and no-heat request paths", "Phone-forward service calls", "Maintenance and replacement options separated", "Service areas stated before the form"],
  contactPrompt: "Tell Northwind what is happening, whether comfort is currently out, your city, and whether this is repair, maintenance, replacement, or a financing question.",
  localCoverageIntro: "This HVAC sample keeps comfort outcomes first and confirms local service fit before estimate or follow-up steps.",
  localNeighborhoods: ["Minneapolis", "St. Paul", "Edina", "Bloomington", "Plymouth"],
    proofHeadline: "Real HVAC situations, shown without fake results.",
    contactTitle: "Tell Northwind what is happening.",
    formTitle: "Request service",
    formButtonLabel: "Request Service",
    primaryCtaLabel: "Request Service",
  },
  {
    slug: "harbor-wellness",
    systemKey: "harbor",
    systemName: "Harbor",
    name: "Harbor Wellness Clinic",
    category: "Wellness clinic",
    location: "Charleston, SC",
    badge: "Sample Business",
    tagline: "Physical therapy, mobility care, and recovery visits in a calm clinical setting.",
    headline: "Care that feels clear before the first appointment.",
    description: "A trust-first clinic website for services, appointment requests, care approach, and visit details.",
    phoneLabel: "(843) 555-0116",
    phoneHref: "tel:+18435550116",
    email: "care@harborwellness.example",
    address: "78 Queen St, Charleston, SC 29401",
    hours: ["Monday-Thursday 8am-6pm", "Friday 8am-3pm", "New patient consults by appointment"],
    heroImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Bright wellness clinic room with treatment table",
    accent: "#2563eb",
    dark: "#16324f",
    soft: "#eef6fb",
    nav: nav("/templates/sample/harbor-wellness", "Care", "Approach"),
    servicesLabel: "Care services",
    servicesIntro: "Medical and wellness sites should reduce anxiety with plain-language services and visit expectations.",
    services: [
      { name: "Mobility Assessment", meta: "First visit planning", body: "A structured intake to understand movement limits, pain patterns, and goals." },
      { name: "Physical Therapy", meta: "Plan-based sessions", body: "Guided therapeutic exercise and progress checks for everyday function." },
      { name: "Sports Recovery", meta: "Return-to-activity", body: "Care plans for runners, cyclists, weekend athletes, and active adults." },
      { name: "Posture & Desk Pain", meta: "Neck, back, shoulders", body: "Assessment and exercise guidance for workday discomfort and repetitive strain." },
      { name: "Balance & Strength", meta: "Confidence and stability", body: "Practical strength and balance support for daily movement." },
      { name: "Home Exercise Plans", meta: "Between-visit support", body: "Simple routines and clear instructions to continue progress outside the clinic." },
    ],
    proofLabel: "Care approach",
    proofIntro: "For a healthcare-adjacent sample, proof means process and clarity, not fake outcomes.",
    proofItems: ["Intake conversation", "Movement screen", "Plan explanation", "Home exercise handout", "Progress check", "Next-visit planning"],
    aboutHeadline: "A calm clinic website for people comparing care options.",
    aboutBody: "Harbor Wellness Clinic is a fictional sample built to show how a wellness provider can explain services, appointments, and ownership of care without overclaiming results.",
  trust: ["Plain-language care pages", "Appointment request path", "Calm clinical imagery", "No medical promises or testimonials"],
  contactPrompt: "Share what you are hoping to work on, whether this is a new issue, and your preferred appointment window.",
  localCoverageIntro: "This wellness sample shows clear local visit framing and appointment-first communication for neighboring clinics and treatment planning.",
  serviceArea: {
    dma: "Charleston metro",
    coverageCopy: "This sample shows a practical service footprint for nearby Charleston neighborhoods before a visit is requested.",
    cityGroups: [
      { city: "Charleston", neighborhoods: ["Downtown", "West Ashley", "Moultrie", "South of Broad"] },
      { city: "Mount Pleasant", neighborhoods: ["Old Village", "Hollingsworth", "Wando Highlands"] },
      { city: "North Charleston", neighborhoods: ["Northwoods", "Dauphin", "Pine Grove"] },
    ],
  },
  localNeighborhoods: ["Charleston", "Downtown Charleston", "West Ashley", "Moultrie"],
  localSection: {
    eyebrow: "Visit context",
    title: "Confirm care areas before booking an appointment.",
    body: "A clinic should make it easy to confirm neighborhood reach, visit expectations, and communication paths before asking for a full consultation.",
    items: ["Charleston", "Mount Pleasant", "North Charleston", "Daniel Island", "West Ashley"],
  },
  },
  {
    slug: "atlas-advisory",
    systemKey: "atlas",
    systemName: "Atlas",
    name: "Atlas Advisory Group",
    category: "Business consulting",
    location: "Austin, TX",
    badge: "Sample Business",
    tagline: "Operations, growth planning, and decision support for service businesses.",
    headline: "Sharper operating decisions without another full-time hire.",
    description: "A consultant sample website with clear offers, authority, process, and consultation paths.",
    phoneLabel: "(512) 555-0161",
    phoneHref: "tel:+15125550161",
    email: "hello@atlasadvisory.example",
    address: "1101 E 6th St, Austin, TX 78702",
    hours: ["Monday-Friday 9am-5pm", "Consultations by appointment", "Remote advisory available"],
    heroImage: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Consulting team reviewing strategy in a bright office",
    accent: "#4f46e5",
    dark: "#17172f",
    soft: "#f1f2ff",
    nav: nav("/templates/sample/atlas-advisory", "Services", "Approach"),
    servicesLabel: "Advisory services",
    servicesIntro: "Professional-services sites need crisp offers, who they are for, and a low-friction consultation path.",
    services: [
      { name: "Operations Review", meta: "2-week diagnostic", body: "Map current workflows, bottlenecks, handoffs, and practical next improvements." },
      { name: "Growth Planning", meta: "Quarterly roadmap", body: "Prioritize offers, channels, team capacity, and the next moves that matter." },
      { name: "Process Documentation", meta: "SOP cleanup", body: "Turn recurring work into repeatable checklists and owner-ready operating notes." },
      { name: "Leadership Dashboards", meta: "Decision views", body: "Define the metrics and weekly views needed to manage service delivery." },
      { name: "Vendor Selection", meta: "Tool and partner support", body: "Compare options, clarify requirements, and avoid overbuying software." },
      { name: "Monthly Advisory", meta: "Retainer support", body: "Focused operating support for founders who need a steady outside view." },
    ],
    proofLabel: "Approach",
    proofIntro: "Consulting proof can show process and decision clarity without inventing client wins.",
    proofItems: ["Discovery call", "Workflow map", "Priority matrix", "Roadmap session", "Operating dashboard", "Founder handoff"],
    aboutHeadline: "A professional-services site that sells clarity, not fluff.",
    aboutBody: "Atlas Advisory Group is a fictional consulting sample built for authority, service fit, process clarity, and consultation conversion.",
  trust: ["Specific advisory offers", "Consultation-first CTA", "Process-led proof", "No fake case studies"],
  contactPrompt: "Share what kind of operating problem you are trying to solve and what decision you need to make next.",
  localCoverageIntro: "This advisory sample presents a local office context while staying open to remote consultation paths and practical next steps.",
  serviceArea: {
    dma: "Austin metro",
    coverageCopy: "The firm sample keeps consultation availability clear across nearby neighborhoods before project planning begins.",
    cityGroups: [
      { city: "Austin", neighborhoods: ["South Congress", "Downtown", "North Loop", "East Austin", "West Austin"] },
      { city: "Round Rock", neighborhoods: ["Cypress Creek", "Barton Creek", "Mopac"] },
      { city: "Cedar Park", neighborhoods: ["Easton Park", "Northlake", "Brushy Creek"] },
    ],
  },
  localNeighborhoods: ["Austin", "Downtown", "South Congress", "East Austin"],
  localSection: {
    eyebrow: "Consultation footprint",
    title: "Know where we support clients before scheduling.",
    body: "Professional advisory demos should state practical market context and consultation pathways so prospects can quickly confirm fit.",
    items: ["Austin", "Round Rock", "Cedar Park", "Lakeway"],
  },
  },
  {
    slug: "harbor-legal-group",
    systemKey: "atlas",
    systemName: "Atlas",
    name: "Harbor Legal Group",
    category: "Small law firm",
    location: "Tampa, FL",
    badge: "Sample Business",
    tagline: "Estate planning, small business counsel, contract review, and consultation-focused legal support.",
    headline: "Legal help that starts with a clear next step.",
    description: "A professional law firm sample website with practice areas, attorney story, process notes, and a consultation request path.",
    phoneLabel: "(813) 555-0194",
    phoneHref: "tel:+18135550194",
    email: "hello@harborlegal.example",
    address: "401 E Jackson St, Tampa, FL 33602",
    hours: ["Monday-Friday 9am-5pm", "Consultations by appointment", "Remote consults available"],
    heroImage: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Law office desk with legal books and paperwork",
    accent: "#334155",
    dark: "#121826",
    soft: "#f3f5f8",
    nav: nav("/templates/sample/harbor-legal-group", "Practice Areas", "Process", true),
    servicesLabel: "Practice areas",
    servicesIntro: "A small law firm site should help visitors understand fit, consultation steps, and how to ask for help without making guidance promises.",
    services: [
      { name: "Estate Planning", meta: "Wills and planning conversations", body: "Plain-language planning meetings for families who want documents, next steps, and responsibilities organized." },
      { name: "Small Business Counsel", meta: "Formation and owner questions", body: "Support for common business questions, operating basics, and contract-aware decisions." },
      { name: "Contract Review", meta: "Readable feedback", body: "Review conversations that help clients understand key terms, obligations, and follow-up questions." },
      { name: "Real Estate Review", meta: "Transaction documents", body: "Document review and consultation for selected real estate and closing-related questions." },
      { name: "Probate Guidance", meta: "Next-step orientation", body: "Consultations for families trying to understand required steps and document needs." },
      { name: "Consultations", meta: "Fit and next steps", body: "A short initial conversation to understand the matter and whether the firm may be a fit." },
    ],
    proofLabel: "Process",
    proofIntro: "For a legal sample, trust comes from clarity and restraint: what happens next, what to bring, and how contact works.",
    proofItems: ["Consultation request", "Conflict check note", "Document list", "Practice-area fit", "Next-step email", "Private follow-up"],
    aboutHeadline: "A law firm site that feels professional without overpromising.",
    aboutBody: "Harbor Legal Group is a fictional small law firm sample built to show practice-area clarity, attorney positioning, consultation paths, and appropriate disclaimers without invented reviews, outcomes, or guidance promises.",
    emergencyServiceNote: "For time-sensitive legal deadlines, keep a clear call-forward option and a concise intake note before scheduling.",
    financingTopics: ["Consultation payment terms", "Project-based billing structure", "Retainer planning support"],
    financingIntro: "For longer matters, this sample supports financing-style payment conversation without naming lenders or guaranteed rates.",
    serviceArea: {
      dma: "Tampa DMA",
      coverageCopy: "A legal practice can still include local service clarity so prospects can confirm where office-style assistance is offered.",
      cityGroups: [
        { city: "Tampa", neighborhoods: ["Hyde Park", "Ybor City", "Channelside", "Downtown", "Carrollwood"] },
        { city: "St. Petersburg", neighborhoods: ["Downtown St. Pete", "Grand Central", "Lakewood"] },
        { city: "Clearwater", neighborhoods: ["Tierra Verde", "Dunedin", "Moss Park"] },
        { city: "Sarasota", neighborhoods: ["North Sarasota", "Gulf Gate", "Downtown Sarasota"] },
      ],
    },
  trust: ["Practice-area cards", "Consultation-first CTA", "Professional legal tone", "No fake results or testimonials"],
  contactPrompt: "Share the practice area, a short description of the question, and the best way to contact you. This sample form does not create an attorney-client relationship.",
  localCoverageIntro: "This legal sample includes a practice-area contact context for nearby Florida communities and consultation follow-up.",
  localNeighborhoods: ["Tampa", "St. Petersburg", "Brandon", "Clearwater", "Seminole"],
  localSection: {
    eyebrow: "Consultation fit",
    title: "Local consultation support for nearby markets.",
    body: "The legal sample confirms whether a matter is in-service before request timing and next-step recommendations.",
    items: ["Tampa", "St. Petersburg", "Clearwater", "Largo", "Brandon"],
  },
  },
  {
    slug: "table-and-hearth",
    systemKey: "ember",
    systemName: "Ember",
    name: "Table & Hearth",
    category: "Neighborhood restaurant",
    location: "Savannah, GA",
    badge: "Sample Business",
    tagline: "Wood-fired plates, seasonal sides, and relaxed dinners near Forsyth Park.",
    headline: "A warm table for weeknights and small celebrations.",
    description: "A restaurant sample website with menu highlights, hours, private-event inquiries, and clear visit paths.",
    phoneLabel: "(912) 555-0142",
    phoneHref: "tel:+19125550142",
    email: "hello@tableandhearth.example",
    address: "214 Whitaker St, Savannah, GA 31401",
    hours: ["Tuesday-Thursday 5pm-9pm", "Friday-Saturday 5pm-10pm", "Sunday brunch 10am-2pm"],
    heroImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Warm restaurant table with plated food and wine glasses",
    accent: "#d97706",
    dark: "#301a12",
    soft: "#fff3e0",
    nav: nav("/templates/sample/table-and-hearth", "Menu", "Events"),
    servicesLabel: "Menu highlights",
    servicesIntro: "Restaurants need menu clarity, hours, atmosphere, and a path for reservations or private-event questions.",
    services: [
      { name: "Wood-Fired Chicken", meta: "$28", body: "Herb-roasted chicken, charred lemon, pan jus, and seasonal greens." },
      { name: "Market Flatbread", meta: "$18", body: "Seasonal vegetables, whipped ricotta, herbs, and a crisp hearth crust." },
      { name: "Coastal Fish", meta: "$32", body: "Daily fish preparation with bright sides and simple sauces." },
      { name: "Hearth Burger", meta: "$19", body: "Double patty, smoked cheddar, onion jam, and house pickles." },
      { name: "Sunday Brunch", meta: "10am-2pm", body: "Egg dishes, pastries, coffee, and low-key weekend plates." },
      { name: "Private Table", meta: "Small groups", body: "Family-style menu planning for small celebrations and team dinners." },
    ],
    proofLabel: "Dining moments",
    proofIntro: "Food sites should make the experience tangible without fake reviews.",
    proofItems: ["Dinner service", "Sunday brunch", "Private table", "Seasonal side", "Wine corner", "Open kitchen detail"],
    aboutHeadline: "A restaurant sample built around atmosphere and action.",
    aboutBody: "Table & Hearth is a fictional restaurant sample that shows menu, hours, location, and gathering inquiries in a warm local voice.",
  trust: ["Menu-first structure", "Hours and location up front", "Event inquiry path", "No fake diner reviews"],
  contactPrompt: "Ask about a table, private dinner, menu question, or event date.",
  localCoverageIntro: "This dining sample shows a local neighborhood-first service context for reservations and event planning.",
  localNeighborhoods: ["Downtown Savannah", "Forsyth Park", "Historic District", "River Street"],
  localSection: {
    eyebrow: "Visit neighborhood fit",
    title: "Know if this table fits your neighborhood visit.",
    body: "A restaurant sample should make walkability, reservation timing, and local neighborhood fit clear before a guest sends in an inquiry.",
    items: ["Savannah", "Forsyth Park", "Downtown Savannah", "Historic District", "River Street", "Ardsley Park"],
  },
  },
  {
    slug: "brightwire-electric",
    systemKey: "summit",
    systemName: "Summit",
    name: "Brightwire Electric",
    category: "Electrical service",
    location: "Raleigh, NC",
    badge: "Demo Sample",
    tagline: "Panel upgrades, EV chargers, generators, rewiring, lighting, repairs, and emergency electrical help.",
    headline: "Electrical work built around safety and trust.",
    description: "A premium, trust-first electrical website for homeowners comparing urgent repairs, panel upgrades, EV chargers, generators, and planned wiring projects.",
    phoneLabel: "(919) 555-0147",
    phoneHref: "tel:+19195550147",
    email: "service@brightwireelectric.example",
    address: "Raleigh Metro Demo Area, Raleigh, NC 27601",
    hours: ["Monday-Friday 7am-6pm", "Saturday 8am-1pm", "Emergency safety calls by phone"],
    heroImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Licensed electrician working safely inside an electrical panel",
    accent: "#f97316",
    dark: "#111827",
    soft: "#fff7ed",
    nav: nav("/templates/sample/brightwire-electric", "Services", "Projects", true),
    servicesLabel: "Electrical services",
    servicesIntro: "An electrician website should make safety, licensing, emergency issues, and higher-value upgrade projects easy to understand quickly.",
    services: [
      { name: "Panel Upgrades", meta: "Capacity and safety planning", body: "Clear estimate paths for breaker issues, 200-amp upgrades, added circuits, and home electrical capacity questions." },
      { name: "EV Charger Install", meta: "Level 2 home charging", body: "Help homeowners understand charger placement, panel readiness, permitting, and the next step for installation." },
      { name: "Generators", meta: "Backup power planning", body: "Plan standby generator installs, transfer switches, and backup power options with a consult-first path." },
      { name: "Rewiring", meta: "Old wiring and remodels", body: "Guide whole-home, room-by-room, and remodel wiring conversations with safety-first language." },
      { name: "Lighting", meta: "Interior and exterior updates", body: "Make fixture installs, recessed lighting, landscape lighting, and troubleshooting simple to request." },
      { name: "Electrical Repairs", meta: "Outlets, switches, breakers", body: "Fast help for breaker trips, dead outlets, flickering lights, and troubleshooting calls." },
      { name: "Emergency Service", meta: "Call-first safety issues", body: "Prominent guidance for no power, sparking, burning smell, storm damage, or unsafe electrical symptoms." },
    ],
    proofLabel: "Safety and project proof",
    proofIntro: "Electrical proof should show trust, safety process, upgrade scenarios, and real project context without inventing reviews or credentials.",
    proofItems: ["License and insurance signals", "Panel upgrade checklist", "EV charger readiness", "Generator planning notes", "Rewiring safety path", "Emergency repair triage"],
    aboutHeadline: "A licensed electrical company presented with safety-first confidence.",
    aboutBody: "Brightwire Electric is a fictional Raleigh electrical sample built around homeowner trust: visible safety signals, licensed-work language, urgent repair paths, and high-value upgrade services.",
    emergencyServiceNote: "For sparking, burning smell, no power, or unsafe electrical symptoms, a call-first path should sit near the top of the page.",
    financingTopics: ["Panel upgrades", "EV charger installation", "Generator projects"],
    financingIntro: "For larger electrical projects, this sample keeps financing and estimate language close to upgrade services.",
    serviceArea: {
      dma: "Raleigh-Durham DMA",
      coverageCopy: "Service coverage is organized by city so homeowners can confirm local fit before requesting electrical service.",
      cityGroups: [
        { city: "Raleigh", neighborhoods: ["Downtown", "Five Points", "North Hills", "Brier Creek", "Oakwood"] },
        { city: "Cary", neighborhoods: ["Lochmere", "Preston", "Amberly", "MacGregor"] },
        { city: "Durham", neighborhoods: ["Hope Valley", "Southpoint", "Trinity Park", "Woodcroft"] },
        { city: "Apex", neighborhoods: ["Scotts Mill", "Bella Casa", "Beaver Creek"] },
        { city: "Wake Forest", neighborhoods: ["Heritage", "Holding Village", "Downtown Wake Forest"] },
      ],
    },
    trust: ["License and insurance above the fold", "Safety-first service copy", "EV and panel upgrade paths", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell Brightwire what electrical issue or upgrade you need, whether there is an active safety concern, and where the work is located.",
    primaryCtaLabel: "Request Service",
    contactTitle: "Request electrical service.",
    formTitle: "Request Electrical Service",
    formButtonLabel: "Request Service",
    localCoverageIntro: "This electrical sample makes service-area fit and trust signals visible before a homeowner asks for service.",
    localNeighborhoods: ["Raleigh", "Cary", "Durham", "Apex", "Wake Forest"],
    localSection: {
      eyebrow: "Service-area clarity",
      title: "Know whether Brightwire serves your area before requesting help.",
      body: "Electrical calls need local confidence and clear safety expectations before a homeowner submits details.",
      items: ["Raleigh", "Cary", "Durham", "Apex", "Wake Forest"],
    },
  },
  {
    slug: "bluewave-pools",
    systemKey: "summit",
    systemName: "Summit",
    name: "Bluewave Pool Co.",
    category: "Pool service",
    location: "Tampa, FL",
    badge: "Demo Sample",
    tagline: "Weekly pool maintenance, cleaning, repair, openings, resurfacing, and new pool builds.",
    headline: "Pool service built for clean water, reliable visits, and project proof.",
    description: "A premium pool company website for homeowners comparing weekly maintenance plans, cleanups, repairs, resurfacing, and new pool projects.",
    phoneLabel: "(813) 555-0168",
    phoneHref: "tel:+18135550168",
    email: "service@bluewavepools.example",
    address: "Tampa Bay Demo Service Area, Tampa, FL 33602",
    hours: ["Monday-Friday 7am-5pm", "Saturday 8am-1pm", "Seasonal opening and cleanup quotes by request"],
    heroImage: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Clear backyard swimming pool with blue water ready for weekly pool service",
    accent: "#f97316",
    dark: "#0f172a",
    soft: "#eef8ff",
    nav: nav("/templates/sample/bluewave-pools", "Services", "Gallery", true),
    servicesLabel: "Pool services",
    servicesIntro: "A pool company site should separate weekly service, cleaning, repairs, seasonal work, resurfacing, and new builds so homeowners can choose the right path fast.",
    services: [
      { name: "Weekly Maintenance", meta: "Recurring route service", body: "Start a reliable maintenance plan with water testing, chemicals, brushing, skimming, and equipment checks." },
      { name: "Pool Cleaning", meta: "Green pools and routine cleanups", body: "Clear algae, debris, cloudy water, and neglected pools with a direct cleanup quote path." },
      { name: "Pool Repair", meta: "Pumps, filters, heaters", body: "Request help for pumps, filters, heaters, leaks, lights, automation, and equipment troubleshooting." },
      { name: "Openings & Closings", meta: "Seasonal prep", body: "Book seasonal opening, closing, cover removal, startup, and inspection services before schedules fill." },
      { name: "Resurfacing", meta: "Before and after upgrades", body: "Plan finish updates, tile, coping, and renovation work with gallery-backed proof and estimate steps." },
      { name: "New Builds", meta: "Consultation path", body: "Show high-value pool projects with project stages, visual proof, and a clear consultation request path." },
    ],
    proofLabel: "Before and after proof",
    proofIntro: "Pool proof should show clean-water outcomes, resurfacing transformations, and build progress without fake testimonials or invented results.",
    proofItems: ["Weekly route checklist", "Green-pool cleanup", "Pump repair notes", "Opening and closing schedule", "Resurfacing before and after", "New-build consultation path"],
    aboutHeadline: "A pool company presented around recurring service and visible proof.",
    aboutBody: "Bluewave Pool Co. is a fictional Tampa pool sample built around weekly maintenance plans, seasonal service, repair clarity, and strong before-and-after gallery sections.",
    emergencyServiceNote: "For green water, failed pumps, or urgent equipment concerns, keep a service request path close to the top.",
    financingTopics: ["Pool resurfacing", "Equipment upgrades", "New pool builds"],
    financingIntro: "For larger pool projects, this sample places estimate and financing language next to resurfacing and build galleries.",
    serviceArea: {
      dma: "Tampa Bay DMA",
      coverageCopy: "Service coverage is organized by city so homeowners can confirm weekly route fit before requesting a pool service quote.",
      cityGroups: [
        { city: "Tampa", neighborhoods: ["Hyde Park", "Davis Islands", "Carrollwood", "Westchase", "Seminole Heights"] },
        { city: "St. Petersburg", neighborhoods: ["Old Northeast", "Snell Isle", "Shore Acres", "Crescent Lake"] },
        { city: "Clearwater", neighborhoods: ["Countryside", "Belleair", "Island Estates", "Coachman Ridge"] },
        { city: "Brandon", neighborhoods: ["Bloomingdale", "Valrico", "River Hills"] },
        { city: "Palm Harbor", neighborhoods: ["Crystal Beach", "Ozona", "East Lake"] },
      ],
    },
    trust: ["Weekly maintenance plan CTA", "Before-and-after gallery proof", "Same tech every visit language", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell Bluewave about your pool, whether you need weekly service, cleaning, repair, resurfacing, or a new-build consultation, and where the pool is located.",
    primaryCtaLabel: "Get a Weekly Service Quote",
    contactTitle: "Request pool service.",
    formTitle: "Request Pool Service",
    formButtonLabel: "Request Quote",
    localCoverageIntro: "This pool sample helps homeowners confirm route coverage before requesting recurring service or project estimates.",
    localNeighborhoods: ["Tampa", "St. Petersburg", "Clearwater", "Brandon", "Palm Harbor"],
    localSection: {
      eyebrow: "Route coverage",
      title: "Know whether Bluewave serves your pool before requesting a plan.",
      body: "Weekly service depends on route fit, clear expectations, and simple quote steps before the first visit.",
      items: ["Tampa", "St. Petersburg", "Clearwater", "Brandon", "Palm Harbor"],
    },
  },
  {
    slug: "greenline-irrigation",
    systemKey: "summit",
    systemName: "Summit",
    name: "Greenline Irrigation",
    category: "Lawn irrigation",
    location: "Kansas City, MO",
    badge: "Demo Sample",
    tagline: "Sprinkler installation, repair, spring start-ups, winterization, smart controllers, and drip systems.",
    headline: "Sprinkler service built around the season.",
    description: "A premium irrigation website for homeowners booking spring start-ups, summer repairs, fall blow-outs, and smart water-saving upgrades.",
    phoneLabel: "(816) 555-0129",
    phoneHref: "tel:+18165550129",
    email: "service@greenlineirrigation.example",
    address: "Kansas City Metro Demo Area, Kansas City, MO 64108",
    hours: ["Monday-Friday 7am-5pm", "Saturday seasonal appointments", "Fall winterization routes by schedule"],
    heroImage: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Residential lawn sprinkler watering green grass during irrigation service",
    accent: "#f97316",
    dark: "#102016",
    soft: "#f0fdf4",
    nav: nav("/templates/sample/greenline-irrigation", "Services", "Results", true),
    servicesLabel: "Irrigation services",
    servicesIntro: "An irrigation site should separate installation, repair, start-ups, winterization, smart controllers, and drip systems so homeowners can book the right seasonal service quickly.",
    services: [
      { name: "Installation", meta: "New systems and zones", body: "Plan new sprinkler systems, added zones, coverage changes, and efficient watering layouts." },
      { name: "Sprinkler Repair", meta: "Leaks, heads, controllers", body: "Fast help for broken heads, leaks, dry spots, low pressure, wiring faults, and controller issues." },
      { name: "Spring Start-Up", meta: "Activation and inspection", body: "Turn the system on, inspect zones, adjust heads, test controllers, and prepare the lawn for the season." },
      { name: "Winterization / Blow-Out", meta: "Freeze protection", body: "Schedule fall blow-outs and shut-down service before freeze dates and route calendars fill up." },
      { name: "Smart Controllers", meta: "Water-saving upgrades", body: "Install Wi-Fi and weather-based controllers that adjust schedules and help reduce wasted watering." },
      { name: "Drip Systems", meta: "Beds, gardens, and trees", body: "Add targeted watering for landscape beds, gardens, trees, and high-value plantings." },
    ],
    proofLabel: "Project and result proof",
    proofIntro: "Irrigation proof should show healthy lawns, efficient watering, repair results, and seasonal readiness without fake reviews or invented outcomes.",
    proofItems: ["Spring start-up checklist", "Broken-head repair", "Controller upgrade", "Drip conversion", "Winterization route", "New-zone installation"],
    aboutHeadline: "A sprinkler company presented around seasonal demand and water savings.",
    aboutBody: "Greenline Irrigation is a fictional Kansas City sprinkler sample built around the seasonal service calendar, urgent repairs, smart-controller upgrades, and efficient watering results.",
    emergencyServiceNote: "For active leaks, broken heads, or controller failures, make sprinkler repair easy to request from mobile.",
    financingTopics: ["New irrigation systems", "Smart controller upgrades", "Drip conversions"],
    financingIntro: "For larger irrigation projects, this sample places estimate language close to installation and water-saving upgrade conversations.",
    serviceArea: {
      dma: "Kansas City DMA",
      coverageCopy: "Service coverage is organized by city so homeowners can confirm route fit before booking seasonal sprinkler service.",
      cityGroups: [
        { city: "Kansas City", neighborhoods: ["Brookside", "Waldo", "Northland", "River Market", "Ward Parkway"] },
        { city: "Overland Park", neighborhoods: ["Prairie Village", "Nottingham", "Blue Valley", "Oak Park"] },
        { city: "Lee's Summit", neighborhoods: ["Raintree", "Lakewood", "Longview", "Downtown"] },
        { city: "Lenexa", neighborhoods: ["Old Town", "Falcon Ridge", "Lake Lenexa"] },
        { city: "Olathe", neighborhoods: ["Cedar Creek", "Arbor Creek", "Mahaffie"] },
      ],
    },
    trust: ["Season-aware booking CTAs", "Water-savings upgrade story", "Licensed and insured trust signals", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell Greenline whether you need start-up, repair, winterization, installation, smart controller help, or drip irrigation, and where the system is located.",
    primaryCtaLabel: "Book Your Spring Start-Up",
    contactTitle: "Request sprinkler service.",
    formTitle: "Request Irrigation Service",
    formButtonLabel: "Request Service",
    localCoverageIntro: "This irrigation sample helps homeowners confirm route coverage before requesting seasonal sprinkler service or repairs.",
    localNeighborhoods: ["Kansas City", "Overland Park", "Lee's Summit", "Lenexa", "Olathe"],
    localSection: {
      eyebrow: "Seasonal service coverage",
      title: "Know whether Greenline serves your system before booking.",
      body: "Sprinkler start-ups, repairs, and blow-outs depend on route fit and seasonal availability.",
      items: ["Kansas City", "Overland Park", "Lee's Summit", "Lenexa", "Olathe"],
    },
  },
  {
    slug: "overpro-garage-doors",
    systemKey: "summit",
    systemName: "Summit",
    name: "OverPro Garage Doors",
    category: "Garage Doors service",
    location: "Charlotte, NC",
    badge: "Demo Sample",
    tagline: "A garage door site should separate urgent repair, broken springs, opener issues, replacement doors, tune-ups, and commercial doors so a stuck homeowner can act quickly.",
    headline: "Garage door service built for stuck-door calls.",
    description: "OverPro Garage Doors is a fictional Charlotte garage door sample built for urgent repair calls, opener problems, broken springs, replacement planning, and clear mobile booking.",
    phoneLabel: "(704) 555-0148",
    phoneHref: "tel:+17045550148",
    email: "service@overprodoors.example",
    address: "Charlotte Metro Demo Area, Charlotte, NC 28202",
    hours: ["Monday-Friday 7am-6pm", "Saturday appointments by request", "Urgent requests by phone"],
    heroImage: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Modern home exterior with attached garage for a garage door service website",
    accent: "#f97316",
    dark: "#172033",
    soft: "#eef2f7",
    nav: nav("/templates/sample/overpro-garage-doors", "Services", "Projects", true),
    servicesLabel: "Garage door services",
    servicesIntro: "A garage door site should separate urgent repair, broken springs, opener issues, replacement doors, tune-ups, and commercial doors so a stuck homeowner can act quickly.",
    services: [
      { name: "Garage Door Repair", meta: "Door stuck, noisy, off-track", body: "Fast service paths for doors that will not open, will not close, grind, jam, or look unsafe." },
      { name: "Broken Spring Replacement", meta: "High-tension safety work", body: "Explain spring symptoms clearly and route homeowners to professional help instead of DIY risk." },
      { name: "Opener Repair", meta: "Motors, remotes, sensors", body: "Help visitors describe opener failures, keypad issues, sensor alignment, and noisy operation." },
      { name: "Door Replacement", meta: "Curb appeal and security", body: "Show repair-vs-replace thinking for dented, aging, insulated, or damaged garage doors." },
      { name: "Preventive Tune-Ups", meta: "Rollers, cables, balance", body: "Turn one repair into recurring maintenance with safety checks and smoother operation." },
      { name: "Commercial Doors", meta: "Shops and small facilities", body: "Give local businesses a clear path for roll-up doors, dock doors, and secure access problems." },
    ],
    proofLabel: "Project proof",
    proofIntro: "Garage Doors proof should show real service situations, visual context, and process clarity without fake testimonials or unverifiable claims.",
    proofItems: ["Door-will-not-open request","Broken spring triage","Opener sensor checklist","Replacement style guide","Safety tune-up notes","Commercial door repair path"],
    aboutHeadline: "A garage door company presented around urgency, safety, and repair-vs-replace clarity.",
    aboutBody: "OverPro Garage Doors is a fictional Charlotte garage door sample built for urgent repair calls, opener problems, broken springs, replacement planning, and clear mobile booking.",
    emergencyServiceNote: "Urgent visitors need a fast call or booking path before they keep searching.",
    serviceArea: {
      dma: "Charlotte DMA",
      coverageCopy: "Service coverage is organized by city and neighborhood so visitors can confirm local fit before requesting service.",
      cityGroups: [
        { city: "Charlotte", neighborhoods: ["Dilworth","South End","NoDa","Myers Park","Plaza Midwood"] },
        { city: "Concord", neighborhoods: ["Afton Village","Poplar Tent","Downtown Concord"] },
        { city: "Matthews", neighborhoods: ["Sardis","Stallings","Weddington"] },
        { city: "Huntersville", neighborhoods: ["Birkdale","Northcross","Skybrook"] },
        { city: "Pineville", neighborhoods: ["Park Road","Ballantyne","McCullough"] },
      ],
    },
    trust: ["Trade-specific hero image", "Clear service list", "Local service-area clarity", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell OverPro whether the door opens, whether a spring or cable looks broken, what opener symptoms you see, and where the door is located.",
    primaryCtaLabel: "Book Garage Door Repair",
    contactTitle: "Request garage door service.",
    formTitle: "Request Garage Doors Service",
    formButtonLabel: "Book Garage Door Repair",
    localCoverageIntro: "This sample makes local service-area fit visible before a visitor requests help.",
    localNeighborhoods: ["Charlotte","Concord","Matthews","Huntersville","Pineville"],
    localSection: {
      eyebrow: "Service-area clarity",
      title: "Know whether OverPro serves your area before requesting help.",
      body: "Local service buyers should see coverage, service fit, and next steps before submitting details.",
      items: ["Charlotte","Concord","Matthews","Huntersville","Pineville"],
    },
  },
  {
    slug: "shieldline-pest-control",
    systemKey: "summit",
    systemName: "Summit",
    name: "Shieldline Pest Control",
    category: "Pest Control service",
    location: "Phoenix, AZ",
    badge: "Demo Sample",
    tagline: "A pest control site should split one-time emergencies, recurring plans, termite inspections, rodent exclusion, mosquito service, and commercial pest programs.",
    headline: "Pest control service built for recurring protection.",
    description: "Shieldline Pest Control is a fictional Phoenix pest control sample built for urgent pest problems, recurring plans, termite clarity, rodent exclusion, and easy mobile booking.",
    phoneLabel: "(602) 555-0186",
    phoneHref: "tel:+16025550186",
    email: "service@shieldlinepest.example",
    address: "Phoenix Metro Demo Area, Phoenix, AZ 85004",
    hours: ["Monday-Friday 7am-6pm", "Saturday appointments by request", "Urgent requests by phone"],
    heroImage: "/templates/pest-control-treatment.svg",
    heroAlt: "Pest control treatment equipment with insect and rodent prevention visuals",
    accent: "#f97316",
    dark: "#172033",
    soft: "#fff7ed",
    nav: nav("/templates/sample/shieldline-pest-control", "Services", "Projects", true),
    servicesLabel: "Pest control services",
    servicesIntro: "A pest control site should split one-time emergencies, recurring plans, termite inspections, rodent exclusion, mosquito service, and commercial pest programs.",
    services: [
      { name: "General Pest Control", meta: "Ants, spiders, roaches", body: "Give homeowners a direct request path for common pests and explain the first treatment clearly." },
      { name: "Recurring Protection Plans", meta: "Monthly or quarterly", body: "Turn emergency calls into ongoing prevention with plan details and visit expectations." },
      { name: "Termite Inspections", meta: "High-risk property protection", body: "Separate termite inspections, treatment options, and documentation from general pest pages." },
      { name: "Rodent Control", meta: "Entry points and exclusion", body: "Explain inspection, trapping, sealing, cleanup notes, and follow-up without vague fear tactics." },
      { name: "Mosquito Service", meta: "Seasonal yard treatment", body: "Make outdoor comfort plans easy to compare and book before peak mosquito months." },
      { name: "Emergency Pest Calls", meta: "Wasps, activity, surprises", body: "Provide a call-first path for urgent nest, infestation, or safety concerns." },
    ],
    proofLabel: "Project proof",
    proofIntro: "Pest Control proof should show real service situations, visual context, and process clarity without fake testimonials or unverifiable claims.",
    proofItems: ["First-visit checklist","Quarterly plan reminder","Termite inspection path","Rodent exclusion notes","Mosquito season plan","Emergency nest request"],
    aboutHeadline: "A pest control company presented around trust, urgency, and repeat service.",
    aboutBody: "Shieldline Pest Control is a fictional Phoenix pest control sample built for urgent pest problems, recurring plans, termite clarity, rodent exclusion, and easy mobile booking.",
    emergencyServiceNote: "Urgent visitors need a fast call or booking path before they keep searching.",
    serviceArea: {
      dma: "Phoenix DMA",
      coverageCopy: "Service coverage is organized by city and neighborhood so visitors can confirm local fit before requesting service.",
      cityGroups: [
        { city: "Phoenix", neighborhoods: ["Arcadia","Biltmore","Roosevelt Row","Ahwatukee","Desert Ridge"] },
        { city: "Scottsdale", neighborhoods: ["Old Town","McCormick Ranch","North Scottsdale"] },
        { city: "Tempe", neighborhoods: ["Maple Ash","Broadmor","Riverside"] },
        { city: "Mesa", neighborhoods: ["Dobson Ranch","Eastmark","Las Sendas"] },
        { city: "Glendale", neighborhoods: ["Arrowhead","Westgate","Sahuaro Ranch"] },
      ],
    },
    trust: ["Trade-specific hero image", "Clear service list", "Local service-area clarity", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell Shieldline what pest you are seeing, where activity appears, whether children or pets are present, and whether you want one-time service or a recurring plan.",
    primaryCtaLabel: "Book Pest Control",
    contactTitle: "Request pest control service.",
    formTitle: "Request Pest Control Service",
    formButtonLabel: "Book Pest Control",
    localCoverageIntro: "This sample makes local service-area fit visible before a visitor requests help.",
    localNeighborhoods: ["Phoenix","Scottsdale","Tempe","Mesa","Glendale"],
    localSection: {
      eyebrow: "Service-area clarity",
      title: "Know whether Shieldline serves your area before requesting help.",
      body: "Local service buyers should see coverage, service fit, and next steps before submitting details.",
      items: ["Phoenix","Scottsdale","Tempe","Mesa","Glendale"],
    },
  },
  {
    slug: "evergreen-lawn-landscape",
    systemKey: "summit",
    systemName: "Summit",
    name: "Evergreen Lawn & Landscape",
    category: "Landscaping service",
    location: "Raleigh, NC",
    badge: "Demo Sample",
    tagline: "A landscaping site should make weekly maintenance, seasonal cleanup, mulch, planting, trimming, and small landscape projects easy to compare and request.",
    headline: "Landscaping service built for weekly maintenance.",
    description: "Evergreen Lawn & Landscape is a fictional Raleigh landscaping sample built for weekly maintenance, seasonal cleanups, visual project proof, and fast local estimate requests.",
    phoneLabel: "(919) 555-0174",
    phoneHref: "tel:+19195550174",
    email: "hello@evergreenlawn.example",
    address: "Raleigh Metro Demo Area, Raleigh, NC 27605",
    hours: ["Monday-Friday 7am-6pm", "Saturday appointments by request", "Urgent requests by phone"],
    heroImage: "https://images.unsplash.com/photo-1605117882932-f9e32b03fea9?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Fresh lawn and landscaped planting beds for a lawn care website",
    accent: "#65a30d",
    dark: "#1f2a1f",
    soft: "#f0f7ea",
    nav: nav("/templates/sample/evergreen-lawn-landscape", "Services", "Projects", true),
    servicesLabel: "Lawn and landscape services",
    servicesIntro: "A landscaping site should make weekly maintenance, seasonal cleanup, mulch, planting, trimming, and small landscape projects easy to compare and request.",
    services: [
      { name: "Weekly Lawn Care", meta: "Mow, edge, blow", body: "Turn one search into recurring route work with plan details, visit timing, and clear expectations." },
      { name: "Seasonal Cleanups", meta: "Spring and fall", body: "Capture leaf removal, bed cleanup, pruning, debris haul-off, and seasonal reset demand." },
      { name: "Mulch and Bed Refresh", meta: "Edges, weed control, color", body: "Show fast curb-appeal work with before-and-after proof and simple estimate steps." },
      { name: "Planting Plans", meta: "Shrubs, color, privacy", body: "Help homeowners choose practical planting paths for sun, shade, privacy, and low-maintenance color." },
      { name: "Shrub Trimming", meta: "Shape and health", body: "Separate trimming, pruning, hedge work, and cleanup from generic lawn service copy." },
      { name: "Small Landscape Projects", meta: "Beds, borders, paths", body: "Support higher-ticket projects with photos, scope notes, and quote-first language." },
    ],
    proofLabel: "Project proof",
    proofIntro: "Landscaping proof should show real service situations, visual context, and process clarity without fake testimonials or unverifiable claims.",
    proofItems: ["Weekly route checklist","Spring cleanup","Mulch before and after","Planting plan","Shrub trimming detail","Small border project"],
    aboutHeadline: "A lawn and landscape company presented around recurring care and seasonal timing.",
    aboutBody: "Evergreen Lawn & Landscape is a fictional Raleigh landscaping sample built for weekly maintenance, seasonal cleanups, visual project proof, and fast local estimate requests.",
    emergencyServiceNote: "Urgent visitors need a fast call or booking path before they keep searching.",
    serviceArea: {
      dma: "Raleigh DMA",
      coverageCopy: "Service coverage is organized by city and neighborhood so visitors can confirm local fit before requesting service.",
      cityGroups: [
        { city: "Raleigh", neighborhoods: ["North Hills","Five Points","Cameron Village","Downtown","Oakwood"] },
        { city: "Cary", neighborhoods: ["Preston","West Cary","Lochmere"] },
        { city: "Apex", neighborhoods: ["Downtown Apex","Scotts Mill","Bella Casa"] },
        { city: "Wake Forest", neighborhoods: ["Heritage","Holding Village","Forestville"] },
        { city: "Holly Springs", neighborhoods: ["Sunset Ridge","12 Oaks","Holly Glen"] },
      ],
    },
    trust: ["Trade-specific hero image", "Clear service list", "Local service-area clarity", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell Evergreen your address area, yard size, current condition, and whether you need weekly maintenance, cleanup, planting, mulch, or a project estimate.",
    primaryCtaLabel: "Request Lawn Care",
    contactTitle: "Request landscaping service.",
    formTitle: "Request Landscaping Service",
    formButtonLabel: "Request Lawn Care",
    localCoverageIntro: "This sample makes local service-area fit visible before a visitor requests help.",
    localNeighborhoods: ["Raleigh","Cary","Apex","Wake Forest","Holly Springs"],
    localSection: {
      eyebrow: "Service-area clarity",
      title: "Know whether Evergreen serves your area before requesting help.",
      body: "Local service buyers should see coverage, service fit, and next steps before submitting details.",
      items: ["Raleigh","Cary","Apex","Wake Forest","Holly Springs"],
    },
  },
  {
    slug: "canopy-tree-care",
    systemKey: "summit",
    systemName: "Summit",
    name: "Canopy Tree Care",
    category: "Tree Service service",
    location: "Nashville, TN",
    badge: "Demo Sample",
    tagline: "A tree service site should separate removal, trimming, storm response, emergency hazards, stump grinding, and health assessments so safety and price expectations stay clear.",
    headline: "Tree service service built for safety-first estimates.",
    description: "Canopy Tree Care is a fictional Nashville tree service sample built for high-risk removal, storm calls, trimming estimates, stump grinding, and safety-first local lead capture.",
    phoneLabel: "(615) 555-0139",
    phoneHref: "tel:+16155550139",
    email: "service@canopytreecare.example",
    address: "Nashville Metro Demo Area, Nashville, TN 37203",
    hours: ["Monday-Friday 7am-6pm", "Saturday appointments by request", "Urgent requests by phone"],
    heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Tall mature trees and canopy for a tree service website",
    accent: "#16a34a",
    dark: "#102016",
    soft: "#f0fdf4",
    nav: nav("/templates/sample/canopy-tree-care", "Services", "Projects", true),
    servicesLabel: "Tree care services",
    servicesIntro: "A tree service site should separate removal, trimming, storm response, emergency hazards, stump grinding, and health assessments so safety and price expectations stay clear.",
    services: [
      { name: "Tree Removal", meta: "Hazard, crowding, dead trees", body: "Explain removal planning, access, rigging, cleanup, and estimate steps for high-ticket work." },
      { name: "Tree Trimming", meta: "Clearance and canopy care", body: "Help homeowners request pruning for structure, roof clearance, limbs, and appearance." },
      { name: "Storm Damage", meta: "Fallen limbs and urgent hazards", body: "Make storm calls visible with call-first guidance and safe next steps." },
      { name: "Emergency Tree Work", meta: "Property risk and blocked access", body: "Route dangerous hangs, blocked driveways, and roof impact to immediate contact." },
      { name: "Stump Grinding", meta: "Post-removal cleanup", body: "Show stump removal as a clear add-on with yard restoration expectations." },
      { name: "Tree Health Checks", meta: "Decline and risk signs", body: "Support inspection-style requests for leaning, hollow, diseased, or declining trees." },
    ],
    proofLabel: "Project proof",
    proofIntro: "Tree Service proof should show real service situations, visual context, and process clarity without fake testimonials or unverifiable claims.",
    proofItems: ["Removal safety plan","Storm response triage","Pruning clearance notes","Stump grinding add-on","Crane/access planning","Cleanup walkthrough"],
    aboutHeadline: "A tree service company presented around safety, storm urgency, and visible project proof.",
    aboutBody: "Canopy Tree Care is a fictional Nashville tree service sample built for high-risk removal, storm calls, trimming estimates, stump grinding, and safety-first local lead capture.",
    emergencyServiceNote: "Urgent visitors need a fast call or booking path before they keep searching.",
    serviceArea: {
      dma: "Nashville DMA",
      coverageCopy: "Service coverage is organized by city and neighborhood so visitors can confirm local fit before requesting service.",
      cityGroups: [
        { city: "Nashville", neighborhoods: ["East Nashville","12 South","Belle Meade","Green Hills","Germantown"] },
        { city: "Brentwood", neighborhoods: ["Maryland Farms","Crockett Hills","Concord"] },
        { city: "Franklin", neighborhoods: ["Downtown Franklin","Fieldstone Farms","Cool Springs"] },
        { city: "Hendersonville", neighborhoods: ["Indian Lake","Bluegrass","Walton Ferry"] },
        { city: "Murfreesboro", neighborhoods: ["Blackman","Northfield","Downtown"] },
      ],
    },
    trust: ["Trade-specific hero image", "Clear service list", "Local service-area clarity", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell Canopy what tree is involved, whether anything is on a structure or power line, whether access is blocked, and where the tree is located.",
    primaryCtaLabel: "Request Tree Estimate",
    contactTitle: "Request tree service service.",
    formTitle: "Request Tree Service Service",
    formButtonLabel: "Request Tree Estimate",
    localCoverageIntro: "This sample makes local service-area fit visible before a visitor requests help.",
    localNeighborhoods: ["Nashville","Brentwood","Franklin","Hendersonville","Murfreesboro"],
    localSection: {
      eyebrow: "Service-area clarity",
      title: "Know whether Canopy serves your area before requesting help.",
      body: "Local service buyers should see coverage, service fit, and next steps before submitting details.",
      items: ["Nashville","Brentwood","Franklin","Hendersonville","Murfreesboro"],
    },
  },
  {
    slug: "cornerstone-concrete",
    systemKey: "summit",
    systemName: "Summit",
    name: "Cornerstone Concrete",
    category: "Concrete service",
    location: "Columbus, OH",
    badge: "Demo Sample",
    tagline: "A concrete site should separate driveways, patios, slabs, walkways, repairs, and masonry so visitors can compare project types and request the right estimate.",
    headline: "Concrete service built for before-and-after proof.",
    description: "Cornerstone Concrete is a fictional Columbus concrete sample built for driveway replacement, patios, slabs, masonry, repairs, and before-and-after project confidence.",
    phoneLabel: "(614) 555-0119",
    phoneHref: "tel:+16145550119",
    email: "hello@cornerstoneconcrete.example",
    address: "Columbus Metro Demo Area, Columbus, OH 43215",
    hours: ["Monday-Friday 7am-6pm", "Saturday appointments by request", "Urgent requests by phone"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Concrete and construction worksite for a concrete contractor website",
    accent: "#f97316",
    dark: "#202124",
    soft: "#f5f3ef",
    nav: nav("/templates/sample/cornerstone-concrete", "Services", "Projects", true),
    servicesLabel: "Concrete and masonry services",
    servicesIntro: "A concrete site should separate driveways, patios, slabs, walkways, repairs, and masonry so visitors can compare project types and request the right estimate.",
    services: [
      { name: "Concrete Driveways", meta: "Tear-out and replacement", body: "Show driveway replacement steps, drainage notes, finish options, and estimate expectations." },
      { name: "Patios and Walkways", meta: "Outdoor living and access", body: "Use visual proof to help homeowners picture patio sizes, borders, curves, and finishes." },
      { name: "Slabs and Pads", meta: "Garages, sheds, additions", body: "Explain thickness, prep, reinforcement, access, and scheduling for functional concrete work." },
      { name: "Concrete Repair", meta: "Cracks, settlement, spalling", body: "Help visitors understand when repair is possible and when replacement may be smarter." },
      { name: "Masonry Work", meta: "Steps, walls, brick, block", body: "Separate masonry from flatwork with project examples and material clarity." },
      { name: "Stamped Concrete", meta: "Decorative finishes", body: "Support higher-value finish decisions with gallery images and maintenance expectations." },
    ],
    proofLabel: "Before and after proof",
    proofIntro: "Concrete proof should show real service situations, visual context, and process clarity without fake testimonials or unverifiable claims.",
    proofItems: ["Driveway before and after","Patio finish sample","Slab prep notes","Crack repair comparison","Masonry step detail","Stamped finish gallery"],
    aboutHeadline: "A concrete contractor presented around visual proof, scope clarity, and durable project planning.",
    aboutBody: "Cornerstone Concrete is a fictional Columbus concrete sample built for driveway replacement, patios, slabs, masonry, repairs, and before-and-after project confidence.",
    emergencyServiceNote: "Urgent visitors need a fast call or booking path before they keep searching.",
    serviceArea: {
      dma: "Columbus DMA",
      coverageCopy: "Service coverage is organized by city and neighborhood so visitors can confirm local fit before requesting service.",
      cityGroups: [
        { city: "Columbus", neighborhoods: ["Short North","German Village","Clintonville","Bexley","Worthington"] },
        { city: "Dublin", neighborhoods: ["Bridge Park","Muirfield","Riverside"] },
        { city: "Grove City", neighborhoods: ["Town Center","Hoover Crossing","Meadow Grove"] },
        { city: "Westerville", neighborhoods: ["Uptown","Highlands","Huber Ridge"] },
        { city: "New Albany", neighborhoods: ["Market Square","Lambton Park","Windsor"] },
      ],
    },
    trust: ["Trade-specific hero image", "Clear service list", "Local service-area clarity", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell Cornerstone what concrete project you need, approximate size, current surface condition, access constraints, and whether you want repair or replacement advice.",
    primaryCtaLabel: "Request Concrete Estimate",
    contactTitle: "Request concrete service.",
    formTitle: "Request Concrete Service",
    formButtonLabel: "Request Concrete Estimate",
    localCoverageIntro: "This sample makes local service-area fit visible before a visitor requests help.",
    localNeighborhoods: ["Columbus","Dublin","Grove City","Westerville","New Albany"],
    localSection: {
      eyebrow: "Service-area clarity",
      title: "Know whether Cornerstone serves your area before requesting help.",
      body: "Local service buyers should see coverage, service fit, and next steps before submitting details.",
      items: ["Columbus","Dublin","Grove City","Westerville","New Albany"],
    },
  },
  {
    slug: "brightwash-exterior-cleaning",
    systemKey: "summit",
    systemName: "Summit",
    name: "BrightWash Exterior Cleaning",
    category: "Pressure Washing service",
    location: "Tampa, FL",
    badge: "Demo Sample",
    tagline: "A pressure washing site should separate house washing, driveways, patios, roof soft washing, gutter brightening, and commercial cleaning with fast quote paths.",
    headline: "Pressure washing service built for fast quotes.",
    description: "BrightWash Exterior Cleaning is a fictional Tampa pressure washing sample built for quick quote requests, before-and-after proof, soft washing clarity, and mobile-first booking.",
    phoneLabel: "(813) 555-0126",
    phoneHref: "tel:+18135550126",
    email: "hello@brightwashexterior.example",
    address: "Tampa Bay Demo Service Area, Tampa, FL 33602",
    hours: ["Monday-Friday 7am-6pm", "Saturday appointments by request", "Urgent requests by phone"],
    heroImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1800&q=86",
    heroAlt: "Exterior cleaning service professional for a pressure washing website",
    accent: "#0ea5e9",
    dark: "#0f2437",
    soft: "#eaf6fb",
    nav: nav("/templates/sample/brightwash-exterior-cleaning", "Services", "Projects", true),
    servicesLabel: "Exterior cleaning services",
    servicesIntro: "A pressure washing site should separate house washing, driveways, patios, roof soft washing, gutter brightening, and commercial cleaning with fast quote paths.",
    services: [
      { name: "House Washing", meta: "Siding and exterior grime", body: "Explain soft washing, safe surfaces, mildew removal, and what homeowners should expect." },
      { name: "Driveway Cleaning", meta: "Concrete and pavers", body: "Use before-and-after proof to show instant curb-appeal improvement and easy booking." },
      { name: "Roof Soft Washing", meta: "Stains and algae", body: "Separate roof-safe cleaning from high-pressure washing and explain safety clearly." },
      { name: "Patios and Pool Decks", meta: "Outdoor living areas", body: "Help buyers book cleanups before gatherings, listings, and seasonal use." },
      { name: "Gutter Brightening", meta: "Exterior streak removal", body: "Make add-on services visible beside house washing and driveway cleaning." },
      { name: "Commercial Cleaning", meta: "Storefronts and walkways", body: "Show recurring exterior cleaning options for small commercial properties." },
    ],
    proofLabel: "Before and after proof",
    proofIntro: "Pressure Washing proof should show real service situations, visual context, and process clarity without fake testimonials or unverifiable claims.",
    proofItems: ["Driveway before and after","House wash checklist","Roof soft wash safety note","Patio cleanup result","Gutter brightening add-on","Commercial storefront plan"],
    aboutHeadline: "An exterior cleaning company presented around instant proof and fast booking.",
    aboutBody: "BrightWash Exterior Cleaning is a fictional Tampa pressure washing sample built for quick quote requests, before-and-after proof, soft washing clarity, and mobile-first booking.",
    emergencyServiceNote: "Urgent visitors need a fast call or booking path before they keep searching.",
    serviceArea: {
      dma: "Tampa DMA",
      coverageCopy: "Service coverage is organized by city and neighborhood so visitors can confirm local fit before requesting service.",
      cityGroups: [
        { city: "Tampa", neighborhoods: ["Hyde Park","Davis Islands","Carrollwood","Westchase","Seminole Heights"] },
        { city: "St. Petersburg", neighborhoods: ["Old Northeast","Snell Isle","Crescent Lake"] },
        { city: "Clearwater", neighborhoods: ["Countryside","Belleair","Island Estates"] },
        { city: "Brandon", neighborhoods: ["Bloomingdale","Valrico","River Hills"] },
        { city: "Palm Harbor", neighborhoods: ["Crystal Beach","Ozona","East Lake"] },
      ],
    },
    trust: ["Trade-specific hero image", "Clear service list", "Local service-area clarity", "No fake reviews or unverifiable claims"],
    contactPrompt: "Tell BrightWash what surface needs cleaning, approximate size, stains or algae you see, photos if available, and the property location.",
    primaryCtaLabel: "Book Exterior Cleaning",
    contactTitle: "Request pressure washing service.",
    formTitle: "Request Pressure Washing Service",
    formButtonLabel: "Book Exterior Cleaning",
    localCoverageIntro: "This sample makes local service-area fit visible before a visitor requests help.",
    localNeighborhoods: ["Tampa","St. Petersburg","Clearwater","Brandon","Palm Harbor"],
    localSection: {
      eyebrow: "Service-area clarity",
      title: "Know whether BrightWash serves your area before requesting help.",
      body: "Local service buyers should see coverage, service fit, and next steps before submitting details.",
      items: ["Tampa","St. Petersburg","Clearwater","Brandon","Palm Harbor"],
    },
  },
  {
    slug: "mainline-plumbing",
    systemKey: "foundry",
    systemName: "Foundry",
    name: "Mainline Plumbing Co.",
    category: "Plumbing service",
    location: "Columbus, OH",
    badge: "Sample Business",
    tagline: "Leak repair, drain clearing, water heaters, fixture installs, and service calls.",
    headline: "Plumbing help with the problem stated plainly.",
    description: "A trades website built around urgency, service categories, phone contact, and practical next steps.",
    phoneLabel: "(614) 555-0184",
    phoneHref: "tel:+16145550184",
    email: "service@mainlineplumbing.example",
    address: "780 N High St, Columbus, OH 43215",
    hours: ["Monday-Friday 7am-6pm", "Saturday 8am-1pm", "Priority calls by phone"],
    heroImage: "https://images.unsplash.com/photo-1620653713380-7a34b773fef8?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Water heater and plumbing pipes in a utility room",
    accent: "#f59e0b",
    dark: "#202124",
    soft: "#f5f3ef",
    nav: nav("/templates/sample/mainline-plumbing", "Services", "Work", true),
    servicesLabel: "Plumbing services",
    servicesIntro: "A plumbing site needs urgent categories, clear service scope, and strong phone-first conversion.",
    services: [
      { name: "Leak Repair", meta: "Kitchen, bath, utility", body: "Find and repair visible leaks, fixture leaks, and common supply-line issues." },
      { name: "Drain Clearing", meta: "Slow or blocked drains", body: "Service for sinks, tubs, showers, and main-line symptoms with practical next steps." },
      { name: "Water Heaters", meta: "Repair and replacement", body: "Troubleshooting, replacement planning, and maintenance for tank water heaters." },
      { name: "Fixture Installs", meta: "Faucets and toilets", body: "Replace faucets, toilets, disposals, and basic fixtures cleanly and correctly." },
      { name: "Sump Pumps", meta: "Basement protection", body: "Pump replacement, float checks, and backup recommendations." },
      { name: "Inspection Notes", meta: "Homeowner clarity", body: "Plain-language summaries for observed issues and recommended priorities." },
    ],
    proofLabel: "Service scenarios",
    proofIntro: "Trades proof works best as concrete scenarios and process notes, not fake customer stories.",
    proofItems: ["Utility room repair", "Water heater replacement", "Kitchen faucet install", "Clogged drain call", "Basement pump check", "Service truck checklist"],
    aboutHeadline: "A no-nonsense plumbing site for urgent service calls.",
    aboutBody: "Mainline Plumbing is a fictional trades sample built to show how service categories, urgency, and contact paths can be clear within seconds.",
    emergencyServiceNote: "For active water loss or backups, make the call-to-ask-now path visible before all other options.",
    financingTopics: ["Water heater replacement", "Whole-home repipe planning", "Pump and system upgrades"],
    financingIntro: "For larger plumbing projects, this sample places financing discussion inside the service request path for transparency.",
    serviceArea: {
      dma: "Columbus DMA",
      coverageCopy: "A trade-style sample should communicate neighborhood and city coverage plainly so callers can confirm if a visit is in scope.",
      cityGroups: [
        { city: "Columbus", neighborhoods: ["Short North", "German Village", "Clintonville", "Bexley", "Worthington"] },
        { city: "Dublin", neighborhoods: ["Bridgeport", "Woodruff Farm", "Dublin Heights"] },
        { city: "Worthington", neighborhoods: ["Kessler", "Oakridge", "North Ridge"] },
        { city: "Grove City", neighborhoods: ["Morse Crossing", "South Grove", "Riverside"] },
      ],
    },
  trust: ["Phone-forward repair CTA", "Specific service menu", "Industrial visual style", "No fake emergency claims"],
  contactPrompt: "Tell Mainline where the plumbing issue is, what changed, and whether water is actively leaking.",
  localCoverageIntro: "This plumbing sample ties local call-forward and estimate paths to neighborhoods in the Columbus metro area.",
  localNeighborhoods: ["Columbus", "Bexley", "Dublin", "Grove City", "Worthington"],
  localSection: {
    eyebrow: "Neighborhood service coverage",
    title: "Get a fit check before submitting details.",
    body: "A clear neighborhood snapshot reduces uncertainty and helps the visitor move to emergency or estimate paths faster.",
    items: ["Columbus", "Bexley", "Dublin", "Worthington", "Grove City"],
  },
  },
];

export const SAMPLE_BUSINESS_BY_SLUG = Object.fromEntries(SAMPLE_BUSINESSES.map((business) => [business.slug, business])) as Record<string, SampleBusiness>;

export const samplePath = (business: SampleBusiness, page: SamplePage = "home") => {
  const base = `/templates/sample/${business.slug}`;
  if (page === "home") return base;
  if (page === "proof") return `${base}/work`;
  if (page === "service-area") return `${base}/service-areas`;
  return `${base}/${page}`;
};
