export type ServiceAreaCity = {
  city: string;
  neighborhoods: string[];
};

export type ServiceAreaInfo = {
  dma: string;
  mapLabel?: string;
  coverageCopy: string;
  cityGroups: ServiceAreaCity[];
};

export type SampleBusiness = {
  slug: string;
  systemKey: string;
  systemName: string;
  name: string;
  category: string;
  location: string;
  badge: string;
  tagline: string;
  headline: string;
  description: string;
  phoneLabel: string;
  phoneHref: string;
  email: string;
  address: string;
  hours: string[];
  heroImage: string;
  heroAlt: string;
  serviceSectionImage?: string;
  serviceSectionImageAlt?: string;
  trustSectionImage?: string;
  trustSectionImageAlt?: string;
  accent: string;
  dark: string;
  soft: string;
  nav: { href: string; label: string; page: SamplePage }[];
  servicesLabel: string;
  servicesIntro: string;
  services: { name: string; meta: string; body: string }[];
  proofLabel: string;
  proofIntro: string;
  proofItems: string[];
  aboutHeadline: string;
  aboutBody: string;
  localNeighborhoods?: string[];
  localCoverageIntro?: string;
  trustHeadline?: string;
  trustIntro?: string;
  ownerSection?: {
    eyebrow: string;
    title: string;
    body: string;
    bullets: string[];
    cardTitle: string;
    cardItems: string[];
  };
  localSection?: {
    eyebrow: string;
    title: string;
    body: string;
    items: string[];
  };
  trust: string[];
  contactPrompt: string;
  proofHeadline?: string;
  contactTitle?: string;
  formTitle?: string;
  formButtonLabel?: string;
  primaryCtaLabel?: string;
  emergencyServiceNote?: string;
  financingTopics?: string[];
  financingIntro?: string;
  serviceArea?: ServiceAreaInfo;
};

export type SamplePage = "home" | "services" | "about" | "proof" | "service-area" | "contact";

const nav = (
  base: string,
  servicesLabel = "Services",
  proofLabel = "Work",
  includeServiceArea = false,
) => [
  { href: base, label: "Home", page: "home" as const },
  { href: `${base}/services`, label: servicesLabel, page: "services" as const },
  ...(includeServiceArea ? [{ href: `${base}/service-areas`, label: "Service Areas", page: "service-area" as const }] : []),
  { href: `${base}/about`, label: "About", page: "about" as const },
  { href: `${base}/work`, label: proofLabel, page: "proof" as const },
  { href: `${base}/contact`, label: "Contact", page: "contact" as const },
];

export const SAMPLE_BUSINESSES: SampleBusiness[] = [
  {
    slug: "ridgeline-roofing",
    systemKey: "summit",
    systemName: "Summit",
    name: "Ridgeline Roofing",
    category: "Residential roofing",
    location: "Denver, CO",
    badge: "Sample Business",
    tagline: "Roof repair, replacement, inspections, and storm response for Denver homes.",
    headline: "Roofing built for hail season, sun, and snow.",
    description: "A direct, estimate-first roofing website for homeowners who need to understand services, service area, and next steps fast.",
    phoneLabel: "(303) 555-0198",
    phoneHref: "tel:+13035550198",
    email: "hello@ridgelineroofing.example",
    address: "Denver Metro Demo Area, Denver, CO 80202",
    hours: ["Monday-Friday 7am-6pm", "Saturday 8am-2pm", "Emergency tarping triage by request"],
    heroImage: "https://images.unsplash.com/photo-1635424824849-1b09bdcc55b1?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Roofer working on a residential shingle roof",
    accent: "#f97316",
    dark: "#172033",
    soft: "#eef2f7",
    nav: nav("/templates/sample/ridgeline-roofing", "Services", "Projects", true),
    servicesLabel: "Roofing services",
    servicesIntro: "A roofing site should separate urgent repair, planned replacement, inspection, and insurance-support paths clearly.",
    services: [
      { name: "Roof Replacement", meta: "Asphalt shingle and impact-rated options", body: "Full tear-off planning, ventilation review, material selection, and clean project communication." },
      { name: "Roof Repair", meta: "Leaks, flashing, shingles, vents", body: "Focused repairs for active leaks, lifted shingles, flashing issues, and storm-worn roof details." },
      { name: "Storm Damage", meta: "Hail and wind triage", body: "Inspection photos, temporary protection recommendations, and repair/replacement next steps." },
      { name: "Insurance Claim Support", meta: "Documentation-ready notes", body: "Clear scope notes and photo documentation for homeowner claim conversations." },
      { name: "Roof Inspections", meta: "Buying, selling, or post-storm", body: "Readable roof condition summaries with priority items and maintenance recommendations." },
      { name: "Emergency Tarping", meta: "Temporary protection", body: "Short-term protection planning when water intrusion or storm exposure needs immediate attention." },
    ],
    proofLabel: "Project signals",
    proofIntro: "Project pages should make the work feel concrete without inventing customer testimonials or results.",
    proofItems: ["Hail inspection checklist", "Shingle replacement scope", "Flashing repair detail", "Emergency tarp plan", "Ventilation review", "Final cleanup walkthrough"],
    aboutHeadline: "A roofing company presented with clear service confidence.",
    aboutBody: "Ridgeline Roofing is a fictional Denver roofing sample built around homeowner urgency: visible phone paths, service details, storm context, and straightforward estimate requests.",
    emergencyServiceNote: "Emergency roof openings and storm damage should surface a call-first action.",
    financingTopics: ["Roof replacement", "Storm-related replacement", "Major re-tile projects"],
    financingIntro: "For large jobs, this sample keeps financing language next to replacement and major repair conversations.",
    serviceArea: {
      dma: "Denver DMA",
      coverageCopy: "This service-area structure clarifies which nearby cities are supported before owners request estimates.",
      cityGroups: [
        { city: "Denver", neighborhoods: ["Downtown", "Cap Hill", "Stapleton", "Highland", "Cherry Creek"] },
        { city: "Aurora", neighborhoods: ["Aurora Central", "Skyline", "Green Valley Ranch"] },
        { city: "Lakewood", neighborhoods: ["Downtown Lakewood", "Cultural District", "Morrison"] },
        { city: "Golden", neighborhoods: ["Downtown Golden", "Foothills"] },
        { city: "Englewood", neighborhoods: ["Cherry Hills", "Littleton", "Berkley"] },
      ],
    },
  trust: ["Estimate-first conversion path", "Roofing imagery above the fold", "Service area and emergency language", "No fake reviews or unverifiable claims"],
  contactPrompt: "Tell Ridgeline what happened, what kind of roof you have, and whether there is active leaking.",
  localCoverageIntro: "This sample shows metro coverage for Denver-area roofing with explicit coverage transparency before estimate requests.",
  localNeighborhoods: ["Denver", "Aurora", "Lakewood", "Golden", "Englewood"],
  localSection: {
    eyebrow: "Metro service clarity",
    title: "Confirm coverage before choosing your next step.",
    body: "A homeowner should be able to confirm city coverage, then click repair, replacement, or storm support with confidence.",
    items: ["Denver", "Aurora", "Lakewood", "Golden", "Englewood", "Commerce City"],
  },
  },
  {
    slug: "greenline-landscaping",
    systemKey: "summit",
    systemName: "Summit",
    name: "Greenline Landscaping",
    category: "Landscaping and outdoor services",
    location: "Raleigh, NC",
    badge: "Sample Business",
    tagline: "Seasonal cleanups, lawn care, planting, mulch, and small hardscape projects.",
    headline: "Outdoor spaces that look cared for every week.",
    description: "A high-trust landscaping website for homeowners who want maintenance, refreshes, and clear seasonal service packages.",
    phoneLabel: "(919) 555-0137",
    phoneHref: "tel:+19195550137",
    email: "hello@greenlinelandscaping.example",
    address: "1220 Glenwood Ave, Raleigh, NC 27605",
    hours: ["Monday-Friday 8am-5pm", "Saturday estimates by appointment", "Closed Sunday"],
    heroImage: "https://images.unsplash.com/photo-1605117882932-f9e32b03fea9?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Freshly landscaped front yard with green lawn and planting beds",
    accent: "#65a30d",
    dark: "#1f2a1f",
    soft: "#f0f7ea",
    nav: nav("/templates/sample/greenline-landscaping", "Services", "Projects", true),
    servicesLabel: "Landscaping services",
    servicesIntro: "A landscaping site needs service packages, seasonal timing, and examples of curb-appeal work.",
    services: [
      { name: "Weekly Lawn Care", meta: "Mow, edge, blow", body: "Routine maintenance for tidy yards, clean walkways, and consistent curb appeal." },
      { name: "Seasonal Cleanups", meta: "Spring and fall", body: "Leaf removal, bed cleanup, pruning, and prep for the next growing season." },
      { name: "Mulch & Bed Refresh", meta: "Color and weed control", body: "Fresh mulch, sharp bed edges, and planting-bed cleanup for a quick exterior lift." },
      { name: "Planting Plans", meta: "Shrubs, flowers, privacy", body: "Simple planting recommendations for sun, shade, privacy, and low-maintenance color." },
      { name: "Small Hardscapes", meta: "Stone borders and paths", body: "Walkway refreshes, stone borders, gravel areas, and practical outdoor improvements." },
      { name: "Irrigation Checks", meta: "Coverage and repairs", body: "Basic sprinkler checks, dry-zone notes, and repair recommendations." },
    ],
    proofLabel: "Outdoor work",
    proofIntro: "Landscaping proof can show project types and seasonal moments without pretending to be real client work.",
    proofItems: ["Front bed refresh", "Lawn maintenance route", "Backyard cleanup", "Mulch install", "Stone border detail", "Seasonal planting plan"],
    aboutHeadline: "A local landscaping site with immediate service clarity.",
    aboutBody: "Greenline Landscaping is a fictional Raleigh landscaping sample built for estimate requests, seasonal service education, and fast mobile contact.",
    emergencyServiceNote: "For weather events and urgent heat/cool exposure, keep call-first support at the top of service pages.",
    financingTopics: ["Major landscape refreshes", "Irrigation upgrades", "Small hardscape replacements"],
    financingIntro: "When projects are larger than routine care, this sample surfaces payment timing options alongside project-specific requests.",
    serviceArea: {
      dma: "Raleigh DMA",
      coverageCopy: "A local contractor sample should state coverage clearly so visitors can confirm service fit before reaching out.",
      cityGroups: [
        { city: "Raleigh", neighborhoods: ["North Hills", "Five Points", "Cameron Village", "Downtown"] },
        { city: "Wake Forest", neighborhoods: ["South Wake", "Eastwood", "Forestville"] },
        { city: "Cary", neighborhoods: ["Preston", "West Cary", "Briarcreek"] },
        { city: "Apex", neighborhoods: ["Summerfield", "Muirfield", "Downtown Apex"] },
        { city: "Holly Springs", neighborhoods: ["Holly Square", "East Holly", "Cedar Drive"] },
      ],
    },
  trust: ["Trade-specific hero image", "Clear service list", "Project-style visual cues", "Click-to-call and estimate paths"],
  contactPrompt: "Share your address area, yard size, and whether you need maintenance, cleanup, planting, or a project estimate.",
  localCoverageIntro: "This sample demonstrates area clarity for core Raleigh neighborhoods in a practical exterior-services context.",
  localNeighborhoods: ["Raleigh", "Cary", "Wake Forest", "Apex", "Holly Springs"],
  localSection: {
    eyebrow: "City and neighborhood fit",
    title: "Area confirmation before project planning.",
    body: "This sample should confirm where service coverage applies before users choose seasonal maintenance, plant refresh, or estimate requests.",
    items: ["Raleigh", "Cary", "Apex", "Holly Springs", "Wake Forest"],
  },
  },
  {
    slug: "northstar-air",
    systemKey: "summit",
    systemName: "Summit",
    name: "Northstar Air",
    category: "AC/HVAC service",
    location: "Minneapolis, MN",
    badge: "Sample Business",
    tagline: "AC repair, heating service, maintenance plans, and replacement quotes for Minneapolis homes.",
    headline: "When the house is too hot or too cold, the next step should be obvious.",
    description: "A fictional HVAC sample built around the real moments homeowners care about: no-cool calls, no-heat calls, tune-ups, installs, financing questions, and a fast request-service path.",
    phoneLabel: "(612) 555-0172",
    phoneHref: "tel:+16125550172",
    email: "service@northstarair.example",
    address: "2448 Lyndale Ave S, Minneapolis, MN 55405",
    hours: ["Monday-Friday 7:30am-6pm", "Saturday 8am-2pm", "Priority no-cool and no-heat requests by phone"],
    heroImage: "https://images.pexels.com/photos/32497161/pexels-photo-32497161.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1400&q=80",
    heroAlt: "HVAC technician inspecting an outdoor condenser unit for servicing and diagnostics",
    serviceSectionImage: "https://images.pexels.com/photos/6471911/pexels-photo-6471911.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1400&q=80",
    serviceSectionImageAlt: "Technician checking gauges on an outdoor AC unit during HVAC maintenance",
    trustSectionImage: "/templates/airflow-hvac-desktop.svg",
    trustSectionImageAlt: "HVAC airflow and temperature flow diagram",
    accent: "#0ea5e9",
    dark: "#0f2437",
    soft: "#eaf6fb",
    nav: nav("/templates/sample/northstar-air", "AC/HVAC Services", "Service Proof", true),
    servicesLabel: "AC/HVAC services",
    servicesIntro: "A strong HVAC website separates urgent repair, planned maintenance, replacement installs, air-quality questions, and quote requests so homeowners can choose the right next step fast.",
    services: [
      { name: "Emergency AC Service", meta: "No-cool priority path", body: "For warm air, failed cooling, or a home that cannot comfortably wait until next week. The request path asks what dispatch needs first." },
      { name: "AC Repair", meta: "Cooling diagnostics", body: "Clear help for short cycling, thermostat issues, weak airflow, uneven rooms, strange noises, and cooling systems that cannot keep up." },
      { name: "Heating Repair", meta: "Furnace and heat pump checks", body: "A calm no-heat path for ignition issues, blower problems, thermostat faults, and safety-first repair conversations." },
      { name: "Maintenance Plans", meta: "Spring and fall tune-ups", body: "Seasonal cleaning, inspection, performance checks, filter reminders, and recurring care language homeowners can understand." },
      { name: "Replacement Installs", meta: "Right-sized quote requests", body: "A practical path for aging systems, comfort problems, efficiency goals, financing questions, and replacement estimate requests." },
      { name: "Service Areas", meta: "City and neighborhood coverage", body: "Local service-area copy that helps homeowners quickly confirm whether this HVAC team works near them." },
      { name: "Indoor Air Quality", meta: "Filters, humidity, airflow", body: "Plain-language guidance for filtration, humidity, ventilation, stale rooms, dust concerns, and comfort from room to room." },
      { name: "Financing Questions", meta: "Quote-ready next step", body: "A simple inquiry path for homeowners comparing repair, replacement, payment options, and next-step timing." },
    ],
    proofLabel: "HVAC service proof",
    proofIntro: "Instead of fake testimonials, this sample shows the service situations a real HVAC website should make easy to understand: urgent comfort calls, seasonal maintenance, install estimates, and service-area clarity.",
    proofItems: ["No-cool dispatch path", "Furnace outage request", "Tune-up reminder", "Replacement quote next step", "Financing question", "Service-area confirmation"],
    aboutHeadline: "A local HVAC company homeowners can understand in one minute.",
    aboutBody: "Northstar Air is a fictional Minneapolis HVAC sample with a calm, service-first voice: what is wrong, where the homeowner is, how urgent it is, and what happens next.",
    trustHeadline: "Why homeowners would feel safe calling",
    trustIntro: "Northstar avoids vague contractor language and puts the homeowner's immediate question first: can you help, how do I ask, and what should I expect next?",
    emergencyServiceNote: "When comfort is unsafe, a direct call option should sit near the top of every important page.",
    financingTopics: ["Replacement installs", "Major repairs", "System upgrades"],
    financingIntro: "For high-cost HVAC decisions, show financing options near replacement and upgrade pathways before estimate requests.",
    serviceArea: {
      dma: "Minneapolis DMA",
      coverageCopy: "Service coverage is organized by city and neighborhood so homeowners can confirm local fit before submitting details.",
      cityGroups: [
        { city: "Minneapolis", neighborhoods: ["Downtown", "Northeast", "Southeast", "South Minneapolis", "Nicollet Island"] },
        { city: "St. Paul", neighborhoods: ["Macalester", "Summit Hill", "Summit Avenue", "West Side"] },
        { city: "Bloomington", neighborhoods: ["Normandale", "Wayzata Circle", "Eden Prairie"] },
        { city: "Edina", neighborhoods: ["Morningside", "Highlands", "West Country"] },
        { city: "Plymouth", neighborhoods: ["Meadow Ridge", "The Highlands", "Northridge"] },
      ],
    },
    ownerSection: {
      eyebrow: "Human trust",
      title: "Meet the kind of HVAC company this site is built for.",
      body: "Northstar is written like a small local HVAC team that knows a broken AC is not an abstract service category. It is a hot house, a sleeping baby, an older parent, or a workday interrupted by a system that stopped keeping up.",
      bullets: ["Plain-language repair paths", "No-pressure quote language", "Seasonal maintenance reminders", "A service form that asks what dispatch needs first"],
      cardTitle: "Sample trust language",
      cardItems: ["Local service team", "Repair and replacement guidance", "Respectful in-home communication", "No invented reviews or results"],
    },
    localSection: {
      eyebrow: "Local clarity",
      title: "Built for Minneapolis-area service calls.",
      body: "A real HVAC site should make service areas, urgent availability, maintenance plans, replacement quotes, and financing questions easy to find before someone fills out a form.",
      items: ["Minneapolis", "St. Paul", "Edina", "Bloomington", "Maple Grove", "Plymouth"],
    },
  trust: ["Clear no-cool and no-heat request paths", "Phone-forward service calls", "Maintenance and replacement options separated", "Service areas stated before the form"],
  contactPrompt: "Tell Northstar what is happening, whether comfort is currently out, your city, and whether this is repair, maintenance, replacement, or a financing question.",
  localCoverageIntro: "This HVAC sample keeps comfort outcomes first and confirms local service fit before estimate or follow-up steps.",
  localNeighborhoods: ["Minneapolis", "St. Paul", "Edina", "Bloomington", "Plymouth"],
    proofHeadline: "Real HVAC situations, shown without fake results.",
    contactTitle: "Tell Northstar what is happening.",
    formTitle: "Request service",
    formButtonLabel: "Request Service",
    primaryCtaLabel: "Request Service",
  },
  {
    slug: "harbor-wellness",
    systemKey: "harbor",
    systemName: "Harbor",
    name: "Harbor Wellness Clinic",
    category: "Wellness clinic",
    location: "Charleston, SC",
    badge: "Sample Business",
    tagline: "Physical therapy, mobility care, and recovery visits in a calm clinical setting.",
    headline: "Care that feels clear before the first appointment.",
    description: "A trust-first clinic website for services, appointment requests, care approach, and visit details.",
    phoneLabel: "(843) 555-0116",
    phoneHref: "tel:+18435550116",
    email: "care@harborwellness.example",
    address: "78 Queen St, Charleston, SC 29401",
    hours: ["Monday-Thursday 8am-6pm", "Friday 8am-3pm", "New patient consults by appointment"],
    heroImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Bright wellness clinic room with treatment table",
    accent: "#2563eb",
    dark: "#16324f",
    soft: "#eef6fb",
    nav: nav("/templates/sample/harbor-wellness", "Care", "Approach"),
    servicesLabel: "Care services",
    servicesIntro: "Medical and wellness sites should reduce anxiety with plain-language services and visit expectations.",
    services: [
      { name: "Mobility Assessment", meta: "First visit planning", body: "A structured intake to understand movement limits, pain patterns, and goals." },
      { name: "Physical Therapy", meta: "Plan-based sessions", body: "Guided therapeutic exercise and progress checks for everyday function." },
      { name: "Sports Recovery", meta: "Return-to-activity", body: "Care plans for runners, cyclists, weekend athletes, and active adults." },
      { name: "Posture & Desk Pain", meta: "Neck, back, shoulders", body: "Assessment and exercise guidance for workday discomfort and repetitive strain." },
      { name: "Balance & Strength", meta: "Confidence and stability", body: "Practical strength and balance support for daily movement." },
      { name: "Home Exercise Plans", meta: "Between-visit support", body: "Simple routines and clear instructions to continue progress outside the clinic." },
    ],
    proofLabel: "Care approach",
    proofIntro: "For a healthcare-adjacent sample, proof means process and clarity, not fake outcomes.",
    proofItems: ["Intake conversation", "Movement screen", "Plan explanation", "Home exercise handout", "Progress check", "Next-visit planning"],
    aboutHeadline: "A calm clinic website for people comparing care options.",
    aboutBody: "Harbor Wellness Clinic is a fictional sample built to show how a wellness provider can explain services, appointments, and ownership of care without overclaiming results.",
  trust: ["Plain-language care pages", "Appointment request path", "Calm clinical imagery", "No medical promises or testimonials"],
  contactPrompt: "Share what you are hoping to work on, whether this is a new issue, and your preferred appointment window.",
  localCoverageIntro: "This wellness sample shows clear local visit framing and appointment-first communication for neighboring clinics and treatment planning.",
  serviceArea: {
    dma: "Charleston metro",
    coverageCopy: "This sample shows a practical service footprint for nearby Charleston neighborhoods before a visit is requested.",
    cityGroups: [
      { city: "Charleston", neighborhoods: ["Downtown", "West Ashley", "Moultrie", "South of Broad"] },
      { city: "Mount Pleasant", neighborhoods: ["Old Village", "Hollingsworth", "Wando Highlands"] },
      { city: "North Charleston", neighborhoods: ["Northwoods", "Dauphin", "Pine Grove"] },
    ],
  },
  localNeighborhoods: ["Charleston", "Downtown Charleston", "West Ashley", "Moultrie"],
  localSection: {
    eyebrow: "Visit context",
    title: "Confirm care areas before booking an appointment.",
    body: "A clinic should make it easy to confirm neighborhood reach, visit expectations, and communication paths before asking for a full consultation.",
    items: ["Charleston", "Mount Pleasant", "North Charleston", "Daniel Island", "West Ashley"],
  },
  },
  {
    slug: "atlas-advisory",
    systemKey: "atlas",
    systemName: "Atlas",
    name: "Atlas Advisory Group",
    category: "Business consulting",
    location: "Austin, TX",
    badge: "Sample Business",
    tagline: "Operations, growth planning, and decision support for service businesses.",
    headline: "Sharper operating decisions without another full-time hire.",
    description: "A consultant sample website with clear offers, authority, process, and consultation paths.",
    phoneLabel: "(512) 555-0161",
    phoneHref: "tel:+15125550161",
    email: "hello@atlasadvisory.example",
    address: "1101 E 6th St, Austin, TX 78702",
    hours: ["Monday-Friday 9am-5pm", "Consultations by appointment", "Remote advisory available"],
    heroImage: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Consulting team reviewing strategy in a bright office",
    accent: "#4f46e5",
    dark: "#17172f",
    soft: "#f1f2ff",
    nav: nav("/templates/sample/atlas-advisory", "Services", "Approach"),
    servicesLabel: "Advisory services",
    servicesIntro: "Professional-services sites need crisp offers, who they are for, and a low-friction consultation path.",
    services: [
      { name: "Operations Review", meta: "2-week diagnostic", body: "Map current workflows, bottlenecks, handoffs, and practical next improvements." },
      { name: "Growth Planning", meta: "Quarterly roadmap", body: "Prioritize offers, channels, team capacity, and the next moves that matter." },
      { name: "Process Documentation", meta: "SOP cleanup", body: "Turn recurring work into repeatable checklists and owner-ready operating notes." },
      { name: "Leadership Dashboards", meta: "Decision views", body: "Define the metrics and weekly views needed to manage service delivery." },
      { name: "Vendor Selection", meta: "Tool and partner support", body: "Compare options, clarify requirements, and avoid overbuying software." },
      { name: "Monthly Advisory", meta: "Retainer support", body: "Focused operating support for founders who need a steady outside view." },
    ],
    proofLabel: "Approach",
    proofIntro: "Consulting proof can show process and decision clarity without inventing client wins.",
    proofItems: ["Discovery call", "Workflow map", "Priority matrix", "Roadmap session", "Operating dashboard", "Founder handoff"],
    aboutHeadline: "A professional-services site that sells clarity, not fluff.",
    aboutBody: "Atlas Advisory Group is a fictional consulting sample built for authority, service fit, process clarity, and consultation conversion.",
  trust: ["Specific advisory offers", "Consultation-first CTA", "Process-led proof", "No fake case studies"],
  contactPrompt: "Share what kind of operating problem you are trying to solve and what decision you need to make next.",
  localCoverageIntro: "This advisory sample presents a local office context while staying open to remote consultation paths and practical next steps.",
  serviceArea: {
    dma: "Austin metro",
    coverageCopy: "The firm sample keeps consultation availability clear across nearby neighborhoods before project planning begins.",
    cityGroups: [
      { city: "Austin", neighborhoods: ["South Congress", "Downtown", "North Loop", "East Austin", "West Austin"] },
      { city: "Round Rock", neighborhoods: ["Cypress Creek", "Barton Creek", "Mopac"] },
      { city: "Cedar Park", neighborhoods: ["Easton Park", "Northlake", "Brushy Creek"] },
    ],
  },
  localNeighborhoods: ["Austin", "Downtown", "South Congress", "East Austin"],
  localSection: {
    eyebrow: "Consultation footprint",
    title: "Know where we support clients before scheduling.",
    body: "Professional advisory demos should state practical market context and consultation pathways so prospects can quickly confirm fit.",
    items: ["Austin", "Round Rock", "Cedar Park", "Lakeway"],
  },
  },
  {
    slug: "harbor-legal-group",
    systemKey: "atlas",
    systemName: "Atlas",
    name: "Harbor Legal Group",
    category: "Small law firm",
    location: "Tampa, FL",
    badge: "Sample Business",
    tagline: "Estate planning, small business counsel, contract review, and consultation-focused legal support.",
    headline: "Legal help that starts with a clear next step.",
    description: "A professional law firm sample website with practice areas, attorney story, process notes, and a consultation request path.",
    phoneLabel: "(813) 555-0194",
    phoneHref: "tel:+18135550194",
    email: "hello@harborlegal.example",
    address: "401 E Jackson St, Tampa, FL 33602",
    hours: ["Monday-Friday 9am-5pm", "Consultations by appointment", "Remote consults available"],
    heroImage: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Law office desk with legal books and paperwork",
    accent: "#334155",
    dark: "#121826",
    soft: "#f3f5f8",
    nav: nav("/templates/sample/harbor-legal-group", "Practice Areas", "Process", true),
    servicesLabel: "Practice areas",
    servicesIntro: "A small law firm site should help visitors understand fit, consultation steps, and how to ask for help without making guidance promises.",
    services: [
      { name: "Estate Planning", meta: "Wills and planning conversations", body: "Plain-language planning meetings for families who want documents, next steps, and responsibilities organized." },
      { name: "Small Business Counsel", meta: "Formation and owner questions", body: "Support for common business questions, operating basics, and contract-aware decisions." },
      { name: "Contract Review", meta: "Readable feedback", body: "Review conversations that help clients understand key terms, obligations, and follow-up questions." },
      { name: "Real Estate Review", meta: "Transaction documents", body: "Document review and consultation for selected real estate and closing-related questions." },
      { name: "Probate Guidance", meta: "Next-step orientation", body: "Consultations for families trying to understand required steps and document needs." },
      { name: "Consultations", meta: "Fit and next steps", body: "A short initial conversation to understand the matter and whether the firm may be a fit." },
    ],
    proofLabel: "Process",
    proofIntro: "For a legal sample, trust comes from clarity and restraint: what happens next, what to bring, and how contact works.",
    proofItems: ["Consultation request", "Conflict check note", "Document list", "Practice-area fit", "Next-step email", "Private follow-up"],
    aboutHeadline: "A law firm site that feels professional without overpromising.",
    aboutBody: "Harbor Legal Group is a fictional small law firm sample built to show practice-area clarity, attorney positioning, consultation paths, and appropriate disclaimers without invented reviews, outcomes, or guidance promises.",
    emergencyServiceNote: "For time-sensitive legal deadlines, keep a clear call-forward option and a concise intake note before scheduling.",
    financingTopics: ["Consultation payment terms", "Project-based billing structure", "Retainer planning support"],
    financingIntro: "For longer matters, this sample supports financing-style payment conversation without naming lenders or guaranteed rates.",
    serviceArea: {
      dma: "Tampa DMA",
      coverageCopy: "A legal practice can still include local service clarity so prospects can confirm where office-style assistance is offered.",
      cityGroups: [
        { city: "Tampa", neighborhoods: ["Hyde Park", "Ybor City", "Channelside", "Downtown", "Carrollwood"] },
        { city: "St. Petersburg", neighborhoods: ["Downtown St. Pete", "Grand Central", "Lakewood"] },
        { city: "Clearwater", neighborhoods: ["Tierra Verde", "Dunedin", "Moss Park"] },
        { city: "Sarasota", neighborhoods: ["North Sarasota", "Gulf Gate", "Downtown Sarasota"] },
      ],
    },
  trust: ["Practice-area cards", "Consultation-first CTA", "Professional legal tone", "No fake results or testimonials"],
  contactPrompt: "Share the practice area, a short description of the question, and the best way to contact you. This sample form does not create an attorney-client relationship.",
  localCoverageIntro: "This legal sample includes a practice-area contact context for nearby Florida communities and consultation follow-up.",
  localNeighborhoods: ["Tampa", "St. Petersburg", "Brandon", "Clearwater", "Seminole"],
  localSection: {
    eyebrow: "Consultation fit",
    title: "Local consultation support for nearby markets.",
    body: "The legal sample confirms whether a matter is in-service before request timing and next-step recommendations.",
    items: ["Tampa", "St. Petersburg", "Clearwater", "Largo", "Brandon"],
  },
  },
  {
    slug: "table-and-hearth",
    systemKey: "ember",
    systemName: "Ember",
    name: "Table & Hearth",
    category: "Neighborhood restaurant",
    location: "Savannah, GA",
    badge: "Sample Business",
    tagline: "Wood-fired plates, seasonal sides, and relaxed dinners near Forsyth Park.",
    headline: "A warm table for weeknights and small celebrations.",
    description: "A restaurant sample website with menu highlights, hours, private-event inquiries, and clear visit paths.",
    phoneLabel: "(912) 555-0142",
    phoneHref: "tel:+19125550142",
    email: "hello@tableandhearth.example",
    address: "214 Whitaker St, Savannah, GA 31401",
    hours: ["Tuesday-Thursday 5pm-9pm", "Friday-Saturday 5pm-10pm", "Sunday brunch 10am-2pm"],
    heroImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Warm restaurant table with plated food and wine glasses",
    accent: "#d97706",
    dark: "#301a12",
    soft: "#fff3e0",
    nav: nav("/templates/sample/table-and-hearth", "Menu", "Events"),
    servicesLabel: "Menu highlights",
    servicesIntro: "Restaurants need menu clarity, hours, atmosphere, and a path for reservations or private-event questions.",
    services: [
      { name: "Wood-Fired Chicken", meta: "$28", body: "Herb-roasted chicken, charred lemon, pan jus, and seasonal greens." },
      { name: "Market Flatbread", meta: "$18", body: "Seasonal vegetables, whipped ricotta, herbs, and a crisp hearth crust." },
      { name: "Coastal Fish", meta: "$32", body: "Daily fish preparation with bright sides and simple sauces." },
      { name: "Hearth Burger", meta: "$19", body: "Double patty, smoked cheddar, onion jam, and house pickles." },
      { name: "Sunday Brunch", meta: "10am-2pm", body: "Egg dishes, pastries, coffee, and low-key weekend plates." },
      { name: "Private Table", meta: "Small groups", body: "Family-style menu planning for small celebrations and team dinners." },
    ],
    proofLabel: "Dining moments",
    proofIntro: "Food sites should make the experience tangible without fake reviews.",
    proofItems: ["Dinner service", "Sunday brunch", "Private table", "Seasonal side", "Wine corner", "Open kitchen detail"],
    aboutHeadline: "A restaurant sample built around atmosphere and action.",
    aboutBody: "Table & Hearth is a fictional restaurant sample that shows menu, hours, location, and gathering inquiries in a warm local voice.",
  trust: ["Menu-first structure", "Hours and location up front", "Event inquiry path", "No fake diner reviews"],
  contactPrompt: "Ask about a table, private dinner, menu question, or event date.",
  localCoverageIntro: "This dining sample shows a local neighborhood-first service context for reservations and event planning.",
  localNeighborhoods: ["Downtown Savannah", "Forsyth Park", "Historic District", "River Street"],
  localSection: {
    eyebrow: "Visit neighborhood fit",
    title: "Know if this table fits your neighborhood visit.",
    body: "A restaurant sample should make walkability, reservation timing, and local neighborhood fit clear before a guest sends in an inquiry.",
    items: ["Savannah", "Forsyth Park", "Downtown Savannah", "Historic District", "River Street", "Ardsley Park"],
  },
  },
  {
    slug: "mainline-plumbing",
    systemKey: "foundry",
    systemName: "Foundry",
    name: "Mainline Plumbing",
    category: "Plumbing service",
    location: "Columbus, OH",
    badge: "Sample Business",
    tagline: "Leak repair, drain clearing, water heaters, fixture installs, and service calls.",
    headline: "Plumbing help with the problem stated plainly.",
    description: "A trades website built around urgency, service categories, phone contact, and practical next steps.",
    phoneLabel: "(614) 555-0184",
    phoneHref: "tel:+16145550184",
    email: "service@mainlineplumbing.example",
    address: "780 N High St, Columbus, OH 43215",
    hours: ["Monday-Friday 7am-6pm", "Saturday 8am-1pm", "Priority calls by phone"],
    heroImage: "https://images.unsplash.com/photo-1620653713380-7a34b773fef8?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Water heater and plumbing pipes in a utility room",
    accent: "#f59e0b",
    dark: "#202124",
    soft: "#f5f3ef",
    nav: nav("/templates/sample/mainline-plumbing", "Services", "Work", true),
    servicesLabel: "Plumbing services",
    servicesIntro: "A plumbing site needs urgent categories, clear service scope, and strong phone-first conversion.",
    services: [
      { name: "Leak Repair", meta: "Kitchen, bath, utility", body: "Find and repair visible leaks, fixture leaks, and common supply-line issues." },
      { name: "Drain Clearing", meta: "Slow or blocked drains", body: "Service for sinks, tubs, showers, and main-line symptoms with practical next steps." },
      { name: "Water Heaters", meta: "Repair and replacement", body: "Troubleshooting, replacement planning, and maintenance for tank water heaters." },
      { name: "Fixture Installs", meta: "Faucets and toilets", body: "Replace faucets, toilets, disposals, and basic fixtures cleanly and correctly." },
      { name: "Sump Pumps", meta: "Basement protection", body: "Pump replacement, float checks, and backup recommendations." },
      { name: "Inspection Notes", meta: "Homeowner clarity", body: "Plain-language summaries for observed issues and recommended priorities." },
    ],
    proofLabel: "Service scenarios",
    proofIntro: "Trades proof works best as concrete scenarios and process notes, not fake customer stories.",
    proofItems: ["Utility room repair", "Water heater replacement", "Kitchen faucet install", "Clogged drain call", "Basement pump check", "Service truck checklist"],
    aboutHeadline: "A no-nonsense plumbing site for urgent service calls.",
    aboutBody: "Mainline Plumbing is a fictional trades sample built to show how service categories, urgency, and contact paths can be clear within seconds.",
    emergencyServiceNote: "For active water loss or backups, make the call-to-ask-now path visible before all other options.",
    financingTopics: ["Water heater replacement", "Whole-home repipe planning", "Pump and system upgrades"],
    financingIntro: "For larger plumbing projects, this sample places financing discussion inside the service request path for transparency.",
    serviceArea: {
      dma: "Columbus DMA",
      coverageCopy: "A trade-style sample should communicate neighborhood and city coverage plainly so callers can confirm if a visit is in scope.",
      cityGroups: [
        { city: "Columbus", neighborhoods: ["Short North", "German Village", "Clintonville", "Bexley", "Worthington"] },
        { city: "Dublin", neighborhoods: ["Bridgeport", "Woodruff Farm", "Dublin Heights"] },
        { city: "Worthington", neighborhoods: ["Kessler", "Oakridge", "North Ridge"] },
        { city: "Grove City", neighborhoods: ["Morse Crossing", "South Grove", "Riverside"] },
      ],
    },
  trust: ["Phone-forward repair CTA", "Specific service menu", "Industrial visual style", "No fake emergency claims"],
  contactPrompt: "Tell Mainline where the plumbing issue is, what changed, and whether water is actively leaking.",
  localCoverageIntro: "This plumbing sample ties local call-forward and estimate paths to neighborhoods in the Columbus metro area.",
  localNeighborhoods: ["Columbus", "Bexley", "Dublin", "Grove City", "Worthington"],
  localSection: {
    eyebrow: "Neighborhood service coverage",
    title: "Get a fit check before submitting details.",
    body: "A clear neighborhood snapshot reduces uncertainty and helps the visitor move to emergency or estimate paths faster.",
    items: ["Columbus", "Bexley", "Dublin", "Worthington", "Grove City"],
  },
  },
  {
    slug: "cornerstone-concrete",
    systemKey: "foundry",
    systemName: "Foundry",
    name: "Cornerstone Concrete",
    category: "Concrete contractor",
    location: "Charlotte, NC",
    badge: "Sample Business",
    tagline: "Driveways, patios, slabs, walkways, repairs, and residential concrete estimates.",
    headline: "Concrete work that makes the project scope obvious.",
    description: "A contractor sample website built around project type, finish expectations, service area, and quote requests.",
    phoneLabel: "(704) 555-0186",
    phoneHref: "tel:+17045550186",
    email: "estimates@cornerstoneconcrete.example",
    address: "1420 Camden Rd, Charlotte, NC 28203",
    hours: ["Monday-Friday 7am-5pm", "Saturday estimates by appointment", "Project walk-throughs scheduled by request"],
    heroImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Concrete crew preparing a residential slab form",
    accent: "#78716c",
    dark: "#1c1917",
    soft: "#f5f5f4",
    nav: nav("/templates/sample/cornerstone-concrete", "Services", "Projects", true),
    servicesLabel: "Concrete services",
    servicesIntro: "A concrete contractor site should separate flatwork, repairs, decorative work, and estimate paths so visitors know what to ask for.",
    services: [
      { name: "Driveways", meta: "New pours and replacements", body: "Planning for removal, base prep, drainage, finish options, and clean project sequencing." },
      { name: "Patios", meta: "Outdoor living slabs", body: "Backyard patio pours, broom finishes, borders, and practical layout conversations." },
      { name: "Walkways", meta: "Front entry and side paths", body: "Residential walkways that connect curb appeal, access, grading, and durable finish choices." },
      { name: "Slabs", meta: "Garages, sheds, pads", body: "Small structural pads and utility slabs with plain-language prep and scheduling notes." },
      { name: "Concrete Repair", meta: "Cracks and surface issues", body: "Repair requests framed around condition, safety, drainage, and replacement-versus-repair decisions." },
      { name: "Decorative Concrete", meta: "Borders and finishes", body: "Simple upgrade paths for color, texture, borders, and visible finish details." },
    ],
    proofLabel: "Project proof",
    proofIntro: "Concrete proof should show prep, finish, drainage, and project type without inventing customer stories.",
    proofItems: ["Driveway replacement", "Patio layout", "Walkway form", "Garage slab", "Repair scope", "Finish sample"],
    aboutHeadline: "A contractor sample built for project clarity and estimate requests.",
    aboutBody: "Cornerstone Concrete is a fictional concrete contractor sample showing how a trade site can explain services, local coverage, and quote steps before a homeowner calls.",
    financingTopics: ["Driveway replacement", "Large patio projects", "Garage and accessory slabs"],
    financingIntro: "For larger pours, this sample places financing-style project planning near the quote path without promising terms or approvals.",
    serviceArea: {
      dma: "Charlotte metro",
      coverageCopy: "This concrete sample makes local estimate coverage clear across nearby cities and neighborhoods before a visitor submits project details.",
      cityGroups: [
        { city: "Charlotte", neighborhoods: ["South End", "Dilworth", "NoDa", "Plaza Midwood", "Myers Park"] },
        { city: "Matthews", neighborhoods: ["Stallings", "Sardis", "Providence Estates"] },
        { city: "Huntersville", neighborhoods: ["Birkdale", "Caldwell Station", "Northstone"] },
        { city: "Concord", neighborhoods: ["Afton Village", "Highland Creek", "Poplar Tent"] },
      ],
    },
    trust: ["Project-type service cards", "Estimate-first CTA", "Finish and scope language", "No fake project claims"],
    contactPrompt: "Share the project type, approximate size, surface condition, and whether this is repair or replacement.",
    localCoverageIntro: "This concrete sample ties estimate requests to a practical Charlotte-area service footprint.",
    localNeighborhoods: ["Charlotte", "Matthews", "Huntersville", "Concord", "Pineville"],
    localSection: {
      eyebrow: "Concrete estimate coverage",
      title: "Confirm the project is in range before asking for a quote.",
      body: "A local concrete site should make service coverage and project type clear before the quote form.",
      items: ["Charlotte", "Matthews", "Huntersville", "Concord", "Pineville"],
    },
  },
  {
    slug: "brightwire-electric",
    systemKey: "foundry",
    systemName: "Foundry",
    name: "Brightwire Electric",
    category: "Electrical contractor",
    location: "Nashville, TN",
    badge: "Sample Business",
    tagline: "Panel work, EV chargers, generators, troubleshooting, lighting, and residential electrical service.",
    headline: "Electrical service pages built around safety and next steps.",
    description: "A trade sample website for urgent electrical calls, planned upgrades, and high-trust service requests.",
    phoneLabel: "(615) 555-0172",
    phoneHref: "tel:+16155550172",
    email: "service@brightwireelectric.example",
    address: "905 Woodland St, Nashville, TN 37206",
    hours: ["Monday-Friday 7am-6pm", "Saturday 8am-12pm", "Urgent electrical calls by phone"],
    heroImage: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Electrician working near a residential electrical panel",
    accent: "#f59e0b",
    dark: "#18181b",
    soft: "#fff7ed",
    nav: nav("/templates/sample/brightwire-electric", "Services", "Work", true),
    servicesLabel: "Electrical services",
    servicesIntro: "An electrician site should split urgent repairs, planned upgrades, safety checks, and high-value installs into clear paths.",
    services: [
      { name: "Panel Upgrades", meta: "Capacity and safety planning", body: "Upgrade conversations for older panels, added circuits, and modern home power needs." },
      { name: "EV Chargers", meta: "Home charging installs", body: "Estimate-ready EV charger pages with panel fit, placement, and permitting notes." },
      { name: "Troubleshooting", meta: "Outlets, breakers, lights", body: "Clear contact paths for flickering lights, tripped breakers, dead outlets, and repair questions." },
      { name: "Generator Prep", meta: "Backup power planning", body: "Transfer-switch and load-planning content for homeowners comparing backup options." },
      { name: "Lighting", meta: "Interior and exterior", body: "Fixture replacement, recessed lighting, exterior lighting, and control updates." },
      { name: "Safety Checks", meta: "Home electrical review", body: "Inspection-style request paths for older homes, recent moves, and remodel planning." },
    ],
    proofLabel: "Electrical scenarios",
    proofIntro: "Electrical proof works best as service scenarios, safety process, and scope clarity.",
    proofItems: ["Panel upgrade", "EV charger", "Breaker issue", "Exterior lighting", "Generator prep", "Safety checklist"],
    aboutHeadline: "A safety-first electrician sample for urgent and planned work.",
    aboutBody: "Brightwire Electric is a fictional electrician sample built to show how high-trust trades can organize service pages, safety cues, and contact paths.",
    emergencyServiceNote: "For burning smells, sparks, or active hazards, the sample keeps call-first guidance visible before form requests.",
    financingTopics: ["Panel upgrades", "EV charger installs", "Generator transfer switches"],
    financingIntro: "For larger electrical upgrades, this sample supports financing-style planning notes without promising approvals.",
    serviceArea: {
      dma: "Nashville metro",
      coverageCopy: "This electrical sample shows city and neighborhood coverage so visitors can confirm service fit before submitting details.",
      cityGroups: [
        { city: "Nashville", neighborhoods: ["East Nashville", "12 South", "The Gulch", "Green Hills", "Germantown"] },
        { city: "Franklin", neighborhoods: ["Cool Springs", "Westhaven", "Fieldstone Farms"] },
        { city: "Brentwood", neighborhoods: ["Maryland Farms", "Crockett Hills", "Concord Road"] },
        { city: "Hendersonville", neighborhoods: ["Indian Lake", "Walton Ferry", "Bluegrass"] },
      ],
    },
    trust: ["Safety-forward service language", "Upgrade and repair paths", "Phone-first urgent CTA", "No fake license numbers"],
    contactPrompt: "Tell Brightwire what is happening, whether there is an active safety concern, and what type of electrical work you need.",
    localCoverageIntro: "This electrician sample connects service requests to a local Nashville-area coverage map.",
    localNeighborhoods: ["Nashville", "Franklin", "Brentwood", "Hendersonville", "Mount Juliet"],
    localSection: {
      eyebrow: "Electrical service coverage",
      title: "Make the service area clear before the visitor calls.",
      body: "A strong electrician site reduces hesitation by showing what work is offered and where crews can respond.",
      items: ["Nashville", "Franklin", "Brentwood", "Hendersonville", "Mount Juliet"],
    },
  },
  {
    slug: "overpro-garage-doors",
    systemKey: "summit",
    systemName: "Summit",
    name: "OverPro Garage Doors",
    category: "Garage door service",
    location: "Phoenix, AZ",
    badge: "Sample Business",
    tagline: "Broken springs, openers, door repair, tune-ups, and garage door replacement estimates.",
    headline: "Garage door pages for the stuck-door moment.",
    description: "An exterior-services sample built around urgent repair, replacement choices, and fast quote requests.",
    phoneLabel: "(602) 555-0167",
    phoneHref: "tel:+16025550167",
    email: "help@overprogaragedoors.example",
    address: "118 N Central Ave, Phoenix, AZ 85004",
    hours: ["Monday-Friday 7am-6pm", "Saturday 8am-2pm", "Urgent repair requests by phone"],
    heroImage: "https://images.unsplash.com/photo-1621155346337-1d19476ba7d6?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Modern residential garage door and driveway",
    accent: "#475569",
    dark: "#172033",
    soft: "#eef2f7",
    nav: nav("/templates/sample/overpro-garage-doors", "Services", "Repairs", true),
    servicesLabel: "Garage door services",
    servicesIntro: "A garage door site should make repair, replacement, spring, opener, and tune-up paths easy to scan under pressure.",
    services: [
      { name: "Spring Repair", meta: "Broken or worn springs", body: "Urgent request paths for doors that will not lift, loud breaks, or uneven movement." },
      { name: "Opener Service", meta: "Motors, remotes, sensors", body: "Troubleshooting content for opener issues, sensors, remotes, keypads, and replacement planning." },
      { name: "Door Repair", meta: "Tracks, rollers, cables", body: "Clear language for noisy doors, off-track doors, cable concerns, and hardware replacement." },
      { name: "Door Replacement", meta: "Style and insulation options", body: "Estimate-ready replacement pages with visual priorities, insulation notes, and project timing." },
      { name: "Tune-Ups", meta: "Preventive maintenance", body: "Maintenance content for lubrication, balance checks, rollers, hinges, and opener settings." },
      { name: "Commercial Doors", meta: "Light commercial requests", body: "A simple inquiry path for roll-up doors, storefront service, and small facility needs." },
    ],
    proofLabel: "Repair proof",
    proofIntro: "Garage door proof should show issue types, service process, and replacement options without fake reviews.",
    proofItems: ["Spring replacement", "Opener install", "Track repair", "Door replacement", "Tune-up checklist", "Sensor repair"],
    aboutHeadline: "A garage door sample focused on urgent clarity.",
    aboutBody: "OverPro Garage Doors is a fictional sample for repair-first home services where the visitor may be dealing with a stuck door or a replacement decision.",
    emergencyServiceNote: "When a vehicle is trapped or a door is unsafe, the sample keeps the phone path prominent before slower quote steps.",
    financingTopics: ["Full door replacement", "Insulated door upgrades", "Opener and accessory packages"],
    financingIntro: "Replacement-focused garage door pages can include financing conversations without changing the repair request path.",
    serviceArea: {
      dma: "Phoenix metro",
      coverageCopy: "This sample frames garage door repair coverage across nearby cities so urgent visitors can confirm whether help is in range.",
      cityGroups: [
        { city: "Phoenix", neighborhoods: ["Arcadia", "Downtown", "Ahwatukee", "Desert Ridge", "Encanto"] },
        { city: "Scottsdale", neighborhoods: ["Old Town", "McCormick Ranch", "North Scottsdale"] },
        { city: "Tempe", neighborhoods: ["Maple-Ash", "Broadmor", "South Tempe"] },
        { city: "Mesa", neighborhoods: ["Dobson Ranch", "Las Sendas", "Eastmark"] },
      ],
    },
    trust: ["Urgent repair categories", "Replacement estimate path", "Service-area clarity", "No fake emergency promises"],
    contactPrompt: "Tell OverPro whether the door is stuck, what part seems broken, and whether a vehicle is trapped.",
    localCoverageIntro: "This garage door sample shows repair coverage for a Phoenix-area service business.",
    localNeighborhoods: ["Phoenix", "Scottsdale", "Tempe", "Mesa", "Glendale"],
    localSection: {
      eyebrow: "Garage door coverage",
      title: "Help stuck-door visitors decide whether to call now.",
      body: "Garage door service pages need city coverage and urgent repair options close to the top of the page.",
      items: ["Phoenix", "Scottsdale", "Tempe", "Mesa", "Glendale"],
    },
  },
  {
    slug: "sprinklerworks-irrigation",
    systemKey: "summit",
    systemName: "Summit",
    name: "SprinklerWorks Irrigation",
    category: "Irrigation and sprinkler service",
    location: "Dallas, TX",
    badge: "Sample Business",
    tagline: "Sprinkler repair, seasonal start-ups, winterization, controller upgrades, and water-smart zones.",
    headline: "Irrigation pages built around the service calendar.",
    description: "An outdoor-services sample for seasonal irrigation demand, repair calls, and water-saving upgrade requests.",
    phoneLabel: "(214) 555-0148",
    phoneHref: "tel:+12145550148",
    email: "service@sprinklerworks.example",
    address: "2211 Commerce St, Dallas, TX 75201",
    hours: ["Monday-Friday 7am-5pm", "Saturday seasonal appointments", "Winterization booking by request"],
    heroImage: "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Lawn sprinkler watering a green yard",
    accent: "#0891b2",
    dark: "#12323a",
    soft: "#ecfeff",
    nav: nav("/templates/sample/sprinklerworks-irrigation", "Services", "Seasonal Work", true),
    servicesLabel: "Irrigation services",
    servicesIntro: "Irrigation sites should match seasonal demand with repair, start-up, winterization, and controller upgrade paths.",
    services: [
      { name: "Sprinkler Repair", meta: "Leaks, heads, valves", body: "Repair request language for broken heads, soggy spots, low pressure, and dry zones." },
      { name: "Spring Start-Ups", meta: "Seasonal system opening", body: "Start-up pages that explain zone testing, controller setup, and early-season fixes." },
      { name: "Winterization", meta: "Cold-weather protection", body: "Seasonal booking content for blowouts, shutoff checks, and freeze-prevention reminders." },
      { name: "Controller Upgrades", meta: "Smart watering", body: "Upgrade paths for weather-aware controllers, schedules, and mobile app setup." },
      { name: "Drip Irrigation", meta: "Beds and plantings", body: "Efficient watering options for planting beds, foundation zones, and landscape updates." },
      { name: "Water Audits", meta: "Efficiency checks", body: "Service pages for zone review, overspray, runoff, and practical conservation steps." },
    ],
    proofLabel: "Seasonal proof",
    proofIntro: "Irrigation proof should show seasonal timing, common repairs, and water-saving outcomes without invented numbers.",
    proofItems: ["Broken head repair", "Controller setup", "Zone test", "Winterization", "Drip retrofit", "Water audit"],
    aboutHeadline: "An irrigation sample that follows the service calendar.",
    aboutBody: "SprinklerWorks Irrigation is a fictional irrigation sample showing how seasonal demand, repair urgency, and local coverage can work together.",
    financingTopics: ["Smart controller upgrades", "Multi-zone repairs", "Landscape irrigation retrofits"],
    financingIntro: "For larger irrigation upgrades, this sample frames project planning without promising water savings.",
    serviceArea: {
      dma: "Dallas-Fort Worth metro",
      coverageCopy: "This sample makes seasonal sprinkler service coverage visible across the Dallas area before a visitor books a visit.",
      cityGroups: [
        { city: "Dallas", neighborhoods: ["Lakewood", "Uptown", "Preston Hollow", "Oak Cliff", "M Streets"] },
        { city: "Plano", neighborhoods: ["Legacy West", "Willow Bend", "Downtown Plano"] },
        { city: "Frisco", neighborhoods: ["Stonebriar", "The Trails", "Panther Creek"] },
        { city: "Irving", neighborhoods: ["Las Colinas", "Valley Ranch", "Heritage District"] },
      ],
    },
    trust: ["Seasonal booking paths", "Repair and upgrade services", "Water-smart language", "No fake savings claims"],
    contactPrompt: "Tell SprinklerWorks what season you are booking for, what zone is affected, and whether the system is currently leaking.",
    localCoverageIntro: "This irrigation sample ties seasonal service demand to a Dallas-area coverage footprint.",
    localNeighborhoods: ["Dallas", "Plano", "Frisco", "Irving", "Richardson"],
    localSection: {
      eyebrow: "Irrigation coverage",
      title: "Align service-area clarity with seasonal demand.",
      body: "A strong irrigation page helps visitors choose start-up, repair, winterization, or upgrade paths quickly.",
      items: ["Dallas", "Plano", "Frisco", "Irving", "Richardson"],
    },
  },
  {
    slug: "shieldline-pest-control",
    systemKey: "foundry",
    systemName: "Foundry",
    name: "Shieldline Pest Control",
    category: "Pest control service",
    location: "Orlando, FL",
    badge: "Sample Business",
    tagline: "General pest treatments, termite checks, mosquito service, rodent exclusion, and prevention plans.",
    headline: "Pest control pages for urgent problems and prevention plans.",
    description: "An in-home service sample built around active pest concerns, recurring protection, safety notes, and local service coverage.",
    phoneLabel: "(407) 555-0192",
    phoneHref: "tel:+14075550192",
    email: "help@shieldlinepest.example",
    address: "420 E Church St, Orlando, FL 32801",
    hours: ["Monday-Friday 8am-6pm", "Saturday 8am-1pm", "Urgent pest requests by phone"],
    heroImage: "https://images.unsplash.com/photo-1586280268958-9483002d016a?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Pest control technician preparing residential treatment equipment",
    accent: "#16a34a",
    dark: "#17201a",
    soft: "#f0fdf4",
    nav: nav("/templates/sample/shieldline-pest-control", "Services", "Plans", true),
    servicesLabel: "Pest control services",
    servicesIntro: "A pest control site should separate active infestations, preventive plans, pest-specific services, and treatment expectations.",
    services: [
      { name: "General Pest Control", meta: "Ants, roaches, spiders", body: "Service pages for common indoor and outdoor pests with clear treatment request paths." },
      { name: "Termite Checks", meta: "Inspection requests", body: "Termite-focused content that explains inspection needs, warning signs, and next-step scheduling." },
      { name: "Rodent Exclusion", meta: "Entry-point planning", body: "Rodent pages built around inspection, sealing conversations, and recurring monitoring." },
      { name: "Mosquito Service", meta: "Seasonal yard treatments", body: "Outdoor seasonal service pages for mosquito pressure, event prep, and maintenance plans." },
      { name: "Recurring Plans", meta: "Quarterly protection", body: "Plan content that explains visit cadence, covered pests, and how follow-up requests work." },
      { name: "Move-In Treatments", meta: "New homeowner service", body: "Low-friction service requests for buyers, renters, and property managers before occupancy." },
    ],
    proofLabel: "Service situations",
    proofIntro: "Pest control proof should show pest categories, process clarity, and safety expectations without fake guarantees.",
    proofItems: ["Ant treatment", "Rodent entry check", "Termite inspection", "Mosquito service", "Quarterly plan", "Move-in treatment"],
    aboutHeadline: "A pest control sample with urgency and prevention separated.",
    aboutBody: "Shieldline Pest Control is a fictional pest control sample built to show emergency-style requests, recurring plan paths, and service-area confidence.",
    emergencyServiceNote: "For active infestations or property access concerns, the sample keeps call-first contact visible.",
    financingTopics: ["Termite treatment planning", "Exclusion projects", "Annual prevention plans"],
    financingIntro: "For larger pest-control projects, this sample supports payment conversation near the estimate path without making promises.",
    serviceArea: {
      dma: "Orlando metro",
      coverageCopy: "This sample keeps pest-control service coverage clear across nearby cities and neighborhoods before a visitor sends details.",
      cityGroups: [
        { city: "Orlando", neighborhoods: ["Thornton Park", "College Park", "Lake Nona", "Baldwin Park", "Audubon Park"] },
        { city: "Winter Park", neighborhoods: ["Hannibal Square", "Park Avenue", "Orwin Manor"] },
        { city: "Kissimmee", neighborhoods: ["Celebration", "Poinciana", "Buenaventura Lakes"] },
        { city: "Apopka", neighborhoods: ["Rock Springs", "Errol Estate", "Wekiva"] },
      ],
    },
    trust: ["Pest-specific service cards", "Recurring plan clarity", "Safety-first language", "No fake treatment guarantees"],
    contactPrompt: "Tell Shieldline what pest you are seeing, where it appears, and whether you need one-time help or recurring prevention.",
    localCoverageIntro: "This pest control sample connects urgent and recurring services to an Orlando-area footprint.",
    localNeighborhoods: ["Orlando", "Winter Park", "Kissimmee", "Apopka", "Sanford"],
    localSection: {
      eyebrow: "Pest service coverage",
      title: "Let visitors confirm service fit before sharing details.",
      body: "Pest control buyers need to know both the pest category and whether the service area covers their property.",
      items: ["Orlando", "Winter Park", "Kissimmee", "Apopka", "Sanford"],
    },
  },
  {
    slug: "bluewave-pools",
    systemKey: "summit",
    systemName: "Summit",
    name: "Bluewave Pools",
    category: "Pool service company",
    location: "Tampa, FL",
    badge: "Sample Business",
    tagline: "Weekly pool service, cleaning, repairs, inspections, equipment upgrades, and renovation estimates.",
    headline: "Pool company pages for weekly service and visible proof.",
    description: "An outdoor-services sample built around recurring pool care, repair requests, visual proof, and local service areas.",
    phoneLabel: "(813) 555-0179",
    phoneHref: "tel:+18135550179",
    email: "service@bluewavepools.example",
    address: "1220 E Kennedy Blvd, Tampa, FL 33602",
    hours: ["Monday-Friday 7am-5pm", "Saturday seasonal appointments", "Weekly route requests by form"],
    heroImage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Clean backyard swimming pool and patio",
    accent: "#0284c7",
    dark: "#0f2633",
    soft: "#e0f2fe",
    nav: nav("/templates/sample/bluewave-pools", "Services", "Pool Care", true),
    servicesLabel: "Pool services",
    servicesIntro: "A pool company site should separate weekly service, cleaning, repairs, inspections, and renovation inquiries.",
    services: [
      { name: "Weekly Service", meta: "Route-based maintenance", body: "Recurring care pages for skimming, brushing, water balance, and regular homeowner updates." },
      { name: "Pool Cleaning", meta: "Green-to-clean and one-time visits", body: "One-time cleaning paths for algae, storm debris, move-ins, and neglected pools." },
      { name: "Equipment Repair", meta: "Pumps, filters, heaters", body: "Repair request language for noisy pumps, leaks, filters, heaters, and automation issues." },
      { name: "Pool Inspections", meta: "Home sale and move-in checks", body: "Inspection pages for buyers, sellers, and owners who need condition clarity." },
      { name: "Renovation Estimates", meta: "Surfaces and features", body: "Project inquiry content for resurfacing, tile, lighting, and feature upgrades." },
      { name: "Seasonal Care", meta: "Storm and vacation service", body: "Flexible service paths for storm cleanup, travel coverage, and peak-season needs." },
    ],
    proofLabel: "Pool proof",
    proofIntro: "Pool proof should show service categories, condition examples, and recurring care without fake before-and-after claims.",
    proofItems: ["Weekly route", "Green-to-clean", "Pump repair", "Filter service", "Inspection checklist", "Renovation scope"],
    aboutHeadline: "A pool company sample designed for recurring service.",
    aboutBody: "Bluewave Pools is a fictional pool company sample showing weekly care, repair requests, and project estimates in one local service framework.",
    financingTopics: ["Renovation estimates", "Equipment upgrades", "Automation packages"],
    financingIntro: "For larger pool projects, this sample supports financing-style conversations without listing fake rates.",
    serviceArea: {
      dma: "Tampa Bay area",
      coverageCopy: "This sample makes weekly pool route coverage easy to confirm across Tampa Bay neighborhoods and nearby cities.",
      cityGroups: [
        { city: "Tampa", neighborhoods: ["Hyde Park", "Carrollwood", "Westchase", "Seminole Heights", "Davis Islands"] },
        { city: "St. Petersburg", neighborhoods: ["Old Northeast", "Kenwood", "Snell Isle"] },
        { city: "Clearwater", neighborhoods: ["Countryside", "Sand Key", "Belleair"] },
        { city: "Brandon", neighborhoods: ["Bloomingdale", "Valrico", "Providence Lakes"] },
      ],
    },
    trust: ["Weekly service CTA", "Repair and renovation paths", "Pool-route coverage", "No fake before-and-after claims"],
    contactPrompt: "Tell Bluewave whether you need weekly service, a one-time cleaning, repair help, or a project estimate.",
    localCoverageIntro: "This pool company sample ties weekly route availability to a Tampa Bay coverage map.",
    localNeighborhoods: ["Tampa", "St. Petersburg", "Clearwater", "Brandon", "Riverview"],
    localSection: {
      eyebrow: "Pool route coverage",
      title: "Show where weekly service is available.",
      body: "Pool service pages work better when recurring service and local route coverage are visible before the form.",
      items: ["Tampa", "St. Petersburg", "Clearwater", "Brandon", "Riverview"],
    },
  },
  {
    slug: "brightwash-exterior-cleaning",
    systemKey: "summit",
    systemName: "Summit",
    name: "Brightwash Exterior Cleaning",
    category: "Pressure washing service",
    location: "Raleigh, NC",
    badge: "Sample Business",
    tagline: "House washing, driveway cleaning, roof soft washing, patios, fences, gutters, and exterior estimates.",
    headline: "Pressure washing pages that make the result easy to picture.",
    description: "An exterior-cleaning sample built around visual proof, service categories, and fast quote requests.",
    phoneLabel: "(919) 555-0136",
    phoneHref: "tel:+19195550136",
    email: "quotes@brightwashexterior.example",
    address: "317 W Morgan St, Raleigh, NC 27601",
    hours: ["Monday-Friday 8am-5pm", "Saturday estimates by appointment", "Weather-dependent scheduling"],
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Clean home exterior and driveway after exterior washing",
    accent: "#2563eb",
    dark: "#172033",
    soft: "#eff6ff",
    nav: nav("/templates/sample/brightwash-exterior-cleaning", "Services", "Results", true),
    servicesLabel: "Exterior cleaning services",
    servicesIntro: "Pressure washing pages should separate surface types, show expected fit, and make quote requests low-friction.",
    services: [
      { name: "House Washing", meta: "Siding and exterior surfaces", body: "Soft-wash service pages for siding, trim, mildew, algae, and curb appeal refreshes." },
      { name: "Driveways", meta: "Concrete and pavers", body: "Driveway cleaning content focused on stains, buildup, surface type, and visible results." },
      { name: "Roof Soft Washing", meta: "Low-pressure cleaning", body: "Roof cleaning pages that explain soft-wash expectations and safety-conscious scheduling." },
      { name: "Patios and Decks", meta: "Outdoor living areas", body: "Surface-specific quote paths for patios, decks, pool areas, and outdoor kitchens." },
      { name: "Fence Cleaning", meta: "Wood and vinyl", body: "Cleaning requests for fence lines, gates, algae, and weathered outdoor surfaces." },
      { name: "Gutter Brightening", meta: "Exterior detail cleaning", body: "Add-on service language for visible gutter faces, streaks, and exterior polish." },
    ],
    proofLabel: "Visual proof",
    proofIntro: "Exterior cleaning proof should focus on surfaces, process, and quote context without inventing customer photos.",
    proofItems: ["House wash", "Driveway clean", "Roof soft wash", "Patio refresh", "Fence cleaning", "Gutter brightening"],
    aboutHeadline: "A pressure washing sample designed around fast visual clarity.",
    aboutBody: "Brightwash Exterior Cleaning is a fictional pressure washing sample showing how service categories, quote prompts, and local coverage can convert quickly.",
    financingTopics: ["Multi-surface packages", "Large property cleaning", "HOA and property-manager work"],
    financingIntro: "For larger exterior cleaning packages, this sample frames project scope and payment conversation without naming terms.",
    serviceArea: {
      dma: "Raleigh-Durham area",
      coverageCopy: "This sample makes exterior cleaning coverage visible for homeowners comparing quotes across the Triangle.",
      cityGroups: [
        { city: "Raleigh", neighborhoods: ["Five Points", "North Hills", "Brier Creek", "Oakwood", "Cameron Village"] },
        { city: "Cary", neighborhoods: ["Preston", "Lochmere", "Amberly"] },
        { city: "Durham", neighborhoods: ["Trinity Park", "Southpoint", "Hope Valley"] },
        { city: "Apex", neighborhoods: ["Scotts Mill", "Bella Casa", "Downtown Apex"] },
      ],
    },
    trust: ["Surface-specific service cards", "Quote-first CTA", "Visual proof framing", "No fake before-and-after images"],
    contactPrompt: "Tell Brightwash which surfaces need cleaning, approximate size, and whether there are stains or algae concerns.",
    localCoverageIntro: "This pressure washing sample connects visual service requests to a Raleigh-Durham coverage footprint.",
    localNeighborhoods: ["Raleigh", "Cary", "Durham", "Apex", "Wake Forest"],
    localSection: {
      eyebrow: "Exterior cleaning coverage",
      title: "Make the quote area easy to confirm.",
      body: "Pressure washing buyers often compare quickly, so the page should show service categories and service area immediately.",
      items: ["Raleigh", "Cary", "Durham", "Apex", "Wake Forest"],
    },
  },
  {
    slug: "canopy-tree-care",
    systemKey: "summit",
    systemName: "Summit",
    name: "Canopy Tree Care",
    category: "Tree service company",
    location: "Portland, OR",
    badge: "Sample Business",
    tagline: "Tree removal, pruning, storm cleanup, stump grinding, risk checks, and property-safe estimates.",
    headline: "Tree service pages built around safety and storm urgency.",
    description: "An outdoor-services sample for high-trust tree work, urgent storm requests, and estimate-first service pages.",
    phoneLabel: "(503) 555-0154",
    phoneHref: "tel:+15035550154",
    email: "estimates@canopytreecare.example",
    address: "812 SE Grand Ave, Portland, OR 97214",
    hours: ["Monday-Friday 7am-5pm", "Saturday estimate windows", "Storm cleanup triage by phone"],
    heroImage: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1400&q=82",
    heroAlt: "Tall trees and residential green space",
    accent: "#15803d",
    dark: "#102318",
    soft: "#ecfdf5",
    nav: nav("/templates/sample/canopy-tree-care", "Services", "Work", true),
    servicesLabel: "Tree services",
    servicesIntro: "A tree service site should separate safety-sensitive removal, pruning, storm cleanup, stump work, and risk checks.",
    services: [
      { name: "Tree Removal", meta: "Hazard and project removals", body: "Estimate pages for removals near homes, driveways, fences, utilities, and tight access." },
      { name: "Tree Pruning", meta: "Health and clearance", body: "Pruning service content for canopy health, clearance, view shaping, and seasonal care." },
      { name: "Storm Cleanup", meta: "Urgent fallen limbs", body: "Call-first content for storm damage, blocked access, hanging limbs, and property hazards." },
      { name: "Stump Grinding", meta: "Post-removal cleanup", body: "Simple estimate paths for stump size, location, access, and cleanup preferences." },
      { name: "Risk Checks", meta: "Property safety review", body: "Inspection-style pages for leaning trees, dead limbs, cracks, and homeowner concerns." },
      { name: "Lot Clearing", meta: "Selective clearing", body: "Project inquiry language for small lots, fence lines, and selective clearing needs." },
    ],
    proofLabel: "Safety proof",
    proofIntro: "Tree service proof should show risk categories, equipment planning, and service process without fake emergency claims.",
    proofItems: ["Tree removal", "Canopy pruning", "Storm cleanup", "Stump grinding", "Risk check", "Lot clearing"],
    aboutHeadline: "A tree service sample that keeps safety and scope clear.",
    aboutBody: "Canopy Tree Care is a fictional tree service sample showing how safety-sensitive work can present services, local coverage, and quote paths clearly.",
    emergencyServiceNote: "For fallen limbs, blocked access, or immediate property hazards, the sample keeps phone triage visible before the form.",
    financingTopics: ["Large removals", "Storm cleanup projects", "Multi-tree pruning plans"],
    financingIntro: "For larger tree work, this sample supports project planning and payment conversations without promising approvals.",
    serviceArea: {
      dma: "Portland metro",
      coverageCopy: "This sample maps tree service coverage across Portland-area neighborhoods so visitors can confirm estimate availability.",
      cityGroups: [
        { city: "Portland", neighborhoods: ["Sellwood", "Laurelhurst", "Alameda", "Eastmoreland", "Northwest District"] },
        { city: "Beaverton", neighborhoods: ["Cedar Hills", "Murrayhill", "Raleigh West"] },
        { city: "Lake Oswego", neighborhoods: ["First Addition", "Mountain Park", "Palisades"] },
        { city: "Gresham", neighborhoods: ["Powell Valley", "Hogan Cedars", "Rockwood"] },
      ],
    },
    trust: ["Safety-first service paths", "Storm triage CTA", "Estimate and coverage clarity", "No fake arborist claims"],
    contactPrompt: "Tell Canopy where the tree is, what concern you see, and whether anything is leaning, fallen, or blocking access.",
    localCoverageIntro: "This tree service sample ties urgent and planned work to a Portland-area estimate footprint.",
    localNeighborhoods: ["Portland", "Beaverton", "Lake Oswego", "Gresham", "Tigard"],
    localSection: {
      eyebrow: "Tree service coverage",
      title: "Keep safety-sensitive work tied to clear local coverage.",
      body: "Tree service visitors need to understand whether the crew handles their location and the type of risk involved.",
      items: ["Portland", "Beaverton", "Lake Oswego", "Gresham", "Tigard"],
    },
  },
];

export const SAMPLE_BUSINESS_BY_SLUG = Object.fromEntries(SAMPLE_BUSINESSES.map((business) => [business.slug, business])) as Record<string, SampleBusiness>;

export const samplePath = (business: SampleBusiness, page: SamplePage = "home") => {
  const base = `/templates/sample/${business.slug}`;
  if (page === "home") return base;
  if (page === "proof") return `${base}/work`;
  if (page === "service-area") return `${base}/service-areas`;
  return `${base}/${page}`;
};
